INSERT INTO pojazdy VALUES
(NULL, 'Acura', 'NSX 2017 (U.S. Spec)', 2017, 'USA', 'Street Tier 2', 'Nie', ''),
(NULL, 'Ariel', 'Atom', 2015, 'Wielka Brytania', 'Street Tier 2', 'Tak', 'Czerwony'),
(NULL, 'Aston Martin', 'V8 Vantage S', 2012, 'Wielka Brytania', 'Street Tier 2', 'Nie', ''),
(NULL, 'Aston Martin', 'V12 Vantage Zagato', 2012, 'Wielka Brytania', 'Street Tier 2', 'Nie', ''),
(NULL, 'Aston Martin', 'Vanquish', 2012, 'Wielka Brytania', 'Street Tier 2', 'Nie', ''),
(NULL, 'Audi', 'RS 5 Coupé', 2018, 'Niemcy', 'Street Tier 2', 'Nie', ''),
(NULL, 'Audi', 'RS5 2018 USST Official Edition', 2018, 'Niemcy', 'Street Tier 2', 'Nie', ''),
(NULL, 'Audi', 'R8 Spyder', 2021, 'Niemcy', 'Street Tier 2', 'Tak', 'Czerwony'),
(NULL, 'Audi', 'R8 V10 Plus Coupé', 2016, 'Niemcy', 'Street Tier 2', 'Nie', ''),
(NULL, 'Audi', 'TT RS Coupé 2017', 2017, 'Niemcy', 'Street Tier 2', 'Nie', ''),
(NULL, 'Bentley', 'Continental Supersports 2010', 2010, 'Wielka Brytania', 'Street Tier 2', 'Tak', 'Niebieski'),
(NULL, 'Bentley', 'Mulliner Bacalar', 2020, 'Wielka Brytania', 'Street Tier 2', 'Nie', ''),
(NULL, 'BMW', 'i8 Roadster (I15)', 2018, 'Niemcy', 'Street Tier 2', 'Nie', ''),
(NULL, 'BMW', 'i8 Roadster (I15) Stellar Edition', 2018, 'Niemcy', 'Street Tier 2', 'Nie', ''),
(NULL, 'BMW', 'M2 (F87)', 2017, 'Niemcy', 'Street Tier 1', 'Nie', ''),
(NULL, 'BMW', 'M4 (F82)', 2014, 'Niemcy', 'Street Tier 2', 'Nie', ''),
(NULL, 'BMW', 'M4 Compétition Coupé (G82)', 2021, 'Niemcy', 'Street Tier 2', 'Tak', 'Zielony'),
(NULL, 'BMW', 'M4 Compétition Coupé (G82) Liberty Walk Edition', 2021, 'Niemcy', 'Street Tier 2', 'Tak', 'Pomarańczowy'),
(NULL, 'BMW', 'M5 (F10)', 2011, 'Niemcy', 'Street Tier 2', 'Nie', ''),
(NULL, 'BMW', 'M8 (F92) No Rules Edition', 2019, 'Niemcy', 'Street Tier 2', 'Nie', ''),
(NULL, 'BMW', 'M8 (F92) Performance Edition', 2019, 'Niemcy', 'Street Tier 2', 'Nie', ''),
(NULL, 'BMW', 'M8 Competition Coupe (F92)', 2019, 'Niemcy', 'Street Tier 2', 'Tak', 'Niebieski'),
(NULL, 'BMW', 'M8 Competition Coupe (F92) Interception Unit', 2019, 'Niemcy', 'Street Tier 2', 'Nie', ''),
(NULL, 'BMW', 'X6M (E71)', 2010, 'Niemcy', 'Street Tier 1', 'Nie', ''),
(NULL, 'BMW', 'Z4 M40i (G29)', 2019, 'Niemcy', 'Street Tier 2', 'Nie', ''),
(NULL, 'BMW', 'Z4 M40i (G29) Agent Edition', 2019, 'Niemcy', 'Street Tier 2', 'Nie', ''),
(NULL, 'BMW', 'Z4 M40i (G29) Motorfest Edition', 2019, 'Niemcy', 'Street Tier 2', 'Nie', ''),
(NULL, 'BMW', 'Z4 sDrive35is 2011', 2011, 'Niemcy', 'Street Tier 1', 'Nie', ''),
(NULL, 'Bugatti', 'Type 57 SC Atlantic', 1936, 'Francja', 'Street Tier 1', 'Nie', ''),
(NULL, 'Cadillac', 'Cyclone XP-74 Concept', 1959, 'USA', 'Street Tier 1', 'Nie', ''),
(NULL, 'Cadillac', 'Deville (Coupé)', 1949, 'USA', 'Street Tier 1', 'Nie', ''),
(NULL, 'Cadillac', 'Deville (Coupé) Marcos Cab', 1949, 'USA', 'Street Tier 1', 'Nie', ''),
(NULL, 'Cadillac', 'Eldorado Brougham 1957', 1957, 'USA', 'Street Tier 1', 'Tak', 'Czerwony'),
(NULL, 'Cadillac', 'Escalade', 2012, 'USA', 'Street Tier 1', 'Nie', ''),
(NULL, 'Chevrolet', '3100', 1951, 'USA', 'Street Tier 1', 'Nie', ''),
(NULL, 'Chevrolet', '3100 The Rocket Co.', 1951, 'USA', 'Street Tier 1', 'Nie', ''),
(NULL, 'Chevrolet', 'Camaro RS 1969', 1969, 'USA', 'Street Tier 1', 'Nie', ''),
(NULL, 'Chevrolet', 'Camaro SS 2010', 2010, 'USA', 'Street Tier 2', 'Nie', ''),
(NULL, 'Chevrolet', 'Camaro SS Bend Edition', 2010, 'USA', 'Street Tier 2', 'Nie', ''),
(NULL, 'Chevrolet', 'Camaro Z/28 RS 1971', 1971, 'USA', 'Street Tier 1', 'Tak', 'Zielony'),
(NULL, 'Chevrolet', 'Camaro ZL1 2017', 2017, 'USA', 'Street Tier 2', 'Tak', 'Niebieski'),
(NULL, 'Chevrolet', 'Camaro ZL1 2017 Rift Edition', 2017, 'USA', 'Street Tier 2', 'Nie', ''),
(NULL, 'Chevrolet', 'Chevelle SS 1970', 1970, 'USA', 'Street Tier 1', 'Nie', ''),
(NULL, 'Chevrolet', 'Corvette C2', 1963, 'USA', 'Street Tier 1', 'Nie', ''),
(NULL, 'Chevrolet', 'Corvette C2 2.0 Edition', 1963, 'USA', 'Street Tier 1', 'Nie', ''),
(NULL, 'Chevrolet', 'Corvette C3', 1968, 'USA', 'Street Tier 1', 'Nie', ''),
(NULL, 'Chevrolet', 'Corvette C8 Stingray 2020', 2020, 'USA', 'Street Tier 2', 'Nie', ''),
(NULL, 'Chevrolet', 'Corvette C8 Stingray 2020 Donut Edition', 2020, 'USA', 'Street Tier 2', 'Tak', 'Błękitny'),
(NULL, 'Chevrolet', 'Corvette C8 Stingray 2020 Interception Unit', 2020, 'USA', 'Street Tier 2', 'Nie', ''),
(NULL, 'Chevrolet', 'Corvette Grand Sport', 1963, 'USA', 'Street Tier 1', 'Nie', ''),
(NULL, 'Chevrolet', 'Corvette Grand Sport Armored Edition', 1963, 'USA', 'Street Tier 1', 'Nie', ''),
(NULL, 'Chevrolet', 'Corvette Stingray', 2014, 'USA', 'Street Tier 2', 'Tak', 'Żółty'),
(NULL, 'Chevrolet', 'Corvette ZR1', 2009, 'USA', 'Street Tier 2', 'Tak', 'Czerwony'),
(NULL, 'Chevrolet', 'Impala Sport Sedan', 1967, 'USA', 'Street Tier 1', 'Nie', ''),
(NULL, 'Chevrolet', 'Impala Sport Sedan Naranja Edicion', 1967, 'USA', 'Street Tier 1', 'Nie', ''),
(NULL, 'Chevrolet', 'Impala Sport Sedan Red Duchess Edition', 1967, 'USA', 'Street Tier 1', 'Nie', ''),
(NULL, 'Chevrolet', 'Silverado 1500', 2010, 'USA', 'Street Tier 1', 'Nie', ''),
(NULL, 'Chrysler', '300C SRT8', 2013, 'USA', 'Street Tier 2', 'Nie', ''),
(NULL, 'Chrysler', '300 SRT8 Crown Edition', 2013, 'USA', 'Street Tier 2', 'Nie', ''),
(NULL, 'Chrysler', '300C SRT8 Limousine', 2013, 'USA', 'Street Tier 1', 'Nie', ''),
(NULL, 'DeLorean', 'DMC-12', 1981, 'USA', 'Street Tier 1', 'Nie', ''),
(NULL, 'DeLorean', 'DMC-12 RAD Edition', 1981, 'USA', 'Street Tier 1', 'Nie', ''),
(NULL, 'Dodge', 'Challenger R/T', 1970, 'USA', 'Street Tier 1', 'Tak', 'Niebieski'),
(NULL, 'Dodge', 'Challenger R/T Riff Edition', 1970, 'USA', 'Street Tier 1', 'Nie', ''),
(NULL, 'Dodge', 'Challenger SRT Demon', 2018, 'USA', 'Street Tier 2', 'Nie', ''),
(NULL, 'Dodge', 'Challenger SRT Demon Interception Unit', 2018, 'USA', 'Street Tier 2', 'Nie', ''),
(NULL, 'Dodge', 'Challenger SRT Demon Awaken Edition', 2018, 'USA', 'Street Tier 2', 'Nie', ''),
(NULL, 'Dodge', 'Challenger SRT Hellcat', 2017, 'USA', 'Street Tier 2', 'Tak', 'Czerwony'),
(NULL, 'Dodge', 'Challenger SRT-8 392', 2012, 'USA', 'Street Tier 2', 'Nie', ''),
(NULL, 'Dodge', 'Charger R/T Hemi', 1969, 'USA', 'Street Tier 1', 'Nie', ''),
(NULL, 'Dodge', 'Charger R/T Hemi Masked Edition', 1969, 'USA', 'Street Tier 1', 'Nie', ''),
(NULL, 'Dodge', 'Charger SRT-8', 2012, 'USA', 'Street Tier 2', 'Tak', 'Srebrny'),
(NULL, 'Dodge', 'Charger SRT-8 Lab Edition', 2012, 'USA', 'Street Tier 2', 'Nie', ''),
(NULL, 'Dodge', 'Charger SRT Hellcat Redeye Widebody', 2023, 'USA', 'Street Tier 2', 'Nie', ''),
(NULL, 'Dodge', 'SRT Viper GTS', 2013, 'USA', 'Street Tier 2', 'Nie', ''),
(NULL, 'Dodge', 'SRT Viper GTS Lightning Edition', 2013, 'USA', 'Street Tier 2', 'Nie', ''),
(NULL, 'Dodge', 'Viper SRT-10 Coupe', 2010, 'USA', 'Street Tier 2', 'Nie', ''),
(NULL, 'Ferrari', '308 GTS', 1977, 'Włochy', 'Street Tier 1', 'Nie', ''),
(NULL, 'Ferrari', '512TR', 1991, 'Włochy', 'Street Tier 2', 'Nie', ''),
(NULL, 'Ferrari', 'F12berlinetta', 2013, 'Włochy', 'Street Tier 2', 'Nie', ''),
(NULL, 'Ferrari', 'F40', 1987, 'Włochy', 'Street Tier 2', 'Nie', ''),
(NULL, 'Ford', 'Crown Victoria', 2008, 'USA', 'Street Tier 1', 'Nie', ''),
(NULL, 'Ford', 'Crown Victoria Interception Unit', 2008, 'USA', 'Street Tier 1', 'Nie', ''),
(NULL, 'Ford', 'Crown Victoria Limousine', 2008, 'USA', 'Street Tier 1', 'Nie', ''),
(NULL, 'Ford', 'Crown Victoria Marco_s Cab', 2008, 'USA', 'Street Tier 1', 'Nie', ''),
(NULL, 'Ford', 'F-150 SVT Raptor', 2010, 'USA', 'Street Tier 1', 'Tak', 'Niebieski'),
(NULL, 'Ford', 'Focus RS', 2010, 'USA', 'Street Tier 1', 'Nie', ''),
(NULL, 'Ford', 'Focus RS', 2016, 'USA', 'Street Tier 1', 'Tak', 'Niebieski'),
(NULL, 'Ford', 'GT', 2005, 'USA', 'Street Tier 2', 'Nie', ''),
(NULL, 'Ford', 'Mustang Boss 429', 1969, 'USA', 'Street Tier 1', 'Tak', 'Srebrny'),
(NULL, 'Ford', 'Mustang GT', 2011, 'USA', 'Street Tier 2', 'Tak', 'Pomarańczowy'),
(NULL, 'Ford', 'Mustang GT Convertible', 2024, 'USA', 'Street Tier 2', 'Nie', ''),
(NULL, 'Ford', 'Mustang GT Convertible Motorfest Edition', 2024, 'USA', 'Street Tier 2', 'Tak', 'Zielony'),
(NULL, 'Ford', 'Mustang GT Fastback', 2015, 'USA', 'Street Tier 2', 'Tak', 'Srebrny'),
(NULL, 'Ford', 'Mustang GT Fastback Stunt Edition', 2015, 'USA', 'Street Tier 2', 'Nie', ''),
(NULL, 'Ford', 'Mustang Shelby GT500', 2020, 'USA', 'Street Tier 2', 'Nie', ''),
(NULL, 'Ford', 'Mustang Shelby GT500 Interception Unit', 2020, 'USA', 'Street Tier 2', 'Nie', ''),
(NULL, 'Ford', 'Mustang Shelby GT500 Road Force One', 2020, 'USA', 'Street Tier 2', 'Nie', ''),
(NULL, 'Ford', 'Mustang Shelby GT500 Tribute Edition', 2020, 'USA', 'Street Tier 2', 'Tak', 'Niebieski'),
(NULL, 'Ford', 'Shelby GT500', 2013, 'USA', 'Street Tier 2', 'Nie', ''),
(NULL, 'Forsberg Racing', 'Gold Leader Z (Nissan)', 1975, 'Japonia', 'Street Tier 2', 'Nie', ''),
(NULL, 'Forsberg Racing', 'Nissan 370Z Dominion Edition', 2022, 'Japonia', 'Street Tier 2', 'Nie', ''),
(NULL, 'Honda', 'Civic Type R', 2016, 'Japonia', 'Street Tier 1', 'Nie', ''),
(NULL, 'Honda', 'Civic Type R', 2021, 'Japonia', 'Street Tier 1', 'Tak', 'Czarny'),
(NULL, 'Honda', 'Civic Type R Keola Rapozo Edition', 2021, 'Japonia', 'Street Tier 1', 'Nie', ''),
(NULL, 'Honda', 'NSX', 1992, 'Japonia', 'Street Tier 2', 'Tak', 'Błękitny'),
(NULL, 'Honda', 'S2000 Ultimate Edition', 2009, 'Japonia', 'Street Tier 2', 'Tak', 'Fioletowy'),
(NULL, 'Honda', 'S2000 Ultimate Edition Kamea Hadar Edition', 2009, 'Japonia', 'Street Tier 2', 'Tak', 'Czarny'),
(NULL, 'Honda', 'S2000 Ultimate Edition Motorfest Edition', 2009, 'Japonia', 'Street Tier 2', 'Nie', ''),
(NULL, 'Honda', 'S2000 Ultimate Edition Red Panther Edition', 2009, 'Japonia', 'Street Tier 2', 'Nie', ''),
(NULL, 'Hummer', 'H1 Alpha', 2006, 'USA', 'Street Tier 1', 'Nie', ''),
(NULL, 'Infiniti', 'Q60 Project Black S Concept', 2018, 'Japonia', 'Street Tier 2', 'Nie', ''),
(NULL, 'IVORY-TOWER', 'SSV Mk3', 2023, 'Francja', 'Street Tier 2', 'Tak', 'Niebieski'),
(NULL, 'Jaguar', 'E-Type Series 1 Coupé', 1961, 'Wielka Brytania', 'Street Tier 1', 'Tak', 'Żółty'),
(NULL, 'Jaguar', 'E-Type Series 1 Coupé The Champion Edition', 1961, 'Wielka Brytania', 'Street Tier 1', 'Nie', ''),
(NULL, 'Jaguar', 'E-Type Series 1 Roadster', 1961, 'Wielka Brytania', 'Street Tier 1', 'Nie', ''),
(NULL, 'Jaguar', 'E-Type Series 1 Roadster Temptation Edition', 1961, 'Wielka Brytania', 'Street Tier 1', 'Tak', 'Zielony'),
(NULL, 'Jaguar', 'F-Type SVR Coupe', 2017, 'Wielka Brytania', 'Street Tier 2', 'Nie', ''),
(NULL, 'Jaguar', 'F-Type SVR Coupe Professional Edition', 2017, 'Wielka Brytania', 'Street Tier 2', 'Nie', ''),
(NULL, 'Jeep®', 'Grand Cherokee SRT8®', 2012, 'USA', 'Street Tier 1', 'Nie', ''),
(NULL, 'Jeep®', 'Wrangler - Pioneer Edition', 2012, 'USA', 'Street Tier 1', 'Nie', ''),
(NULL, 'Jeep®', 'Wrangler', 2012, 'USA', 'Street Tier 1', 'Nie', ''),
(NULL, 'KTM', 'X-Bow R', 2016, 'Austria', 'Street Tier 2', 'Nie', ''),
(NULL, 'Lamborghini', 'Countach LP 5000 Quattrovalvole', 1985, 'Włochy', 'Street Tier 2', 'Nie', ''),
(NULL, 'Lamborghini', 'Diablo GT', 1999, 'Włochy', 'Street Tier 2', 'Nie', ''),
(NULL, 'Lamborghini', 'Diablo GT Pura Potenza Edition', 1999, 'Włochy', 'Street Tier 2', 'Tak', 'Pomarańczowy'),
(NULL, 'Lamborghini', 'Gallardo LP 570-4 Superleggera', 2011, 'Włochy', 'Street Tier 2', 'Tak', 'Srebrny'),
(NULL, 'Lamborghini', 'Huracán LP610-4', 2014, 'Włochy', 'Street Tier 2', 'Tak', 'Niebieski'),
(NULL, 'Lamborghini', 'Miura SV', 1971, 'Włochy', 'Street Tier 2', 'Tak', 'Żółty'),
(NULL, 'Lamborghini', 'Murciélago LP640', 2006, 'Włochy', 'Street Tier 2', 'Nie', ''),
(NULL, 'Lamborghini', 'Urus', 2017, 'Włochy', 'Street Tier 2', 'Nie', ''),
(NULL, 'Lotus', 'Evora GTE', 2012, 'Wielka Brytania', 'Street Tier 2', 'Nie', ''),
(NULL, 'Lotus', 'Evora GTE Overcut Edition', 2012, 'Wielka Brytania', 'Street Tier 2', 'Nie', ''),
(NULL, 'Lotus', 'Exige S', 2013, 'Wielka Brytania', 'Street Tier 2', 'Tak', 'Zielony'),
(NULL, 'Maserati', 'GranTurismo S', 2009, 'Włochy', 'Street Tier 2', 'Nie', ''),
(NULL, 'Mazda', 'MX5 (NA)', 1989, 'Japonia', 'Street Tier 1', 'Nie', ''),
(NULL, 'Mazda', 'MX5 (ND)', 2016, 'Japonia', 'Street Tier 2', 'Nie', ''),
(NULL, 'Mazda', 'RX3', 1972, 'Japonia', 'Street Tier 1', 'Nie', ''),
(NULL, 'Mazda', 'RX3 Supercharged Edition', 1972, 'Japonia', 'Street Tier 1', 'Nie', ''),
(NULL, 'Mazda', 'RX7', 2002, 'Japonia', 'Street Tier 2', 'Tak', 'Fioletowy'),
(NULL, 'Mazda', 'RX7 Shirogane Edition', 2002, 'Japonia', 'Street Tier 2', 'Nie', ''),
(NULL, 'Mazda', 'RX7 Turbo 10th Anniversary', 1988, 'Japonia', 'Street Tier 1', 'Tak', 'Srebrny'),
(NULL, 'Mazda', 'RX7 Turbo Sakura Edition', 1988, 'Japonia', 'Street Tier 1', 'Nie', ''),
(NULL, 'Mazda', 'RX8', 2010, 'Japonia', 'Street Tier 2', 'Tak', 'Niebieski'),
(NULL, 'Mazda', 'RX8 Gold Edition', 2010, 'Japonia', 'Street Tier 2', 'Tak', 'Czarny'),
(NULL, 'Mazda', 'RX8 Thunderwave Edition', 2010, 'Japonia', 'Street Tier 2', 'Nie', ''),
(NULL, 'Mazda', 'RX8 Pearl Edition (Edition 03)', 2010, 'Japonia', 'Street Tier 2', 'Nie', ''),
(NULL, 'Mercedes-AMG', 'C 63 Coupé Black Series', 2012, 'Niemcy', 'Street Tier 2', 'Tak', 'Srebrny'),
(NULL, 'Mercedes-AMG', 'C 63 S Coupé', 2016, 'Niemcy', 'Street Tier 2', 'Nie', ''),
(NULL, 'Mercedes-AMG', 'GT', 2015, 'Niemcy', 'Street Tier 2', 'Nie', ''),
(NULL, 'Mercedes-AMG', 'SL 63 (R230)', 2009, 'Niemcy', 'Street Tier 2', 'Nie', ''),
(NULL, 'Mercedes-AMG', 'SLS (C197)', 2010, 'Niemcy', 'Street Tier 2', 'Nie', ''),
(NULL, 'Mercedes-Benz', '300 SLR UHLENHAUT COUPE (W196)', 1955, 'Niemcy', 'Street Tier 1', 'Nie', ''),
(NULL, 'Mercedes-Benz', 'GLC 250 4MATIC Coupé', 2016, 'Niemcy', 'Street Tier 1', 'Nie', ''),
(NULL, 'Mercedes-Benz', 'SLR McLaren 722 Edition', 2007, 'Niemcy', 'Street Tier 2', 'Nie', ''),
(NULL, 'Mini', 'Cooper S (R56)', 2010, 'Wielka Brytania', 'Street Tier 1', 'Nie', ''),
(NULL, 'Mini', 'Cooper S Countryman ALL4 (R60)', 2013, 'Wielka Brytania', 'Street Tier 1', 'Nie', ''),
(NULL, 'Mitsubishi', '3000GT VR4', 1994, 'Japonia', 'Street Tier 2', 'Nie', ''),
(NULL, 'Mitsubishi', '3000GT VR4 Interception Unit', 1994, 'Japonia', 'Street Tier 2', 'Nie', ''),
(NULL, 'Mitsubishi', '3000GT VR4 No Rules Edition', 1994, 'Japonia', 'Street Tier 2', 'Nie', ''),
(NULL, 'Mitsubishi', 'Eclipse GSX', 1999, 'Japonia', 'Street Tier 1', 'Nie', ''),
(NULL, 'Mitsubishi', 'Eclipse GSX Star Edition', 1999, 'Japonia', 'Street Tier 1', 'Nie', ''),
(NULL, 'Mitsubishi', 'FTO GP Version R', 1997, 'Japonia', 'Street Tier 1', 'Nie', ''),
(NULL, 'Mitsubishi', 'FTO Version R Nebula Edition', 1997, 'Japonia', 'Street Tier 1', 'Nie', ''),
(NULL, 'Mitsubishi', 'Lancer Evolution VI GSR', 1999, 'Japonia', 'Street Tier 2', 'Nie', ''),
(NULL, 'Mitsubishi', 'Lancer Evolution X', 2014, 'Japonia', 'Street Tier 2', 'Nie', ''),
(NULL, 'Mitsubishi', 'Lancer Evolution X Black Knight Edition', 2014, 'Japonia', 'Street Tier 2', 'Nie', ''),
(NULL, 'Mitsubishi', 'Lancer Evolution X Red Fury Edition', 2014, 'Japonia', 'Street Tier 2', 'Tak', 'Czarny'),
(NULL, 'Nissan', '240 SX (S14)', 1998, 'Japonia', 'Street Tier 1', 'Nie', ''),
(NULL, 'Nissan', '300 ZX (Z32)', 1994, 'Japonia', 'Street Tier 1', 'Nie', ''),
(NULL, 'Nissan', '300 ZX (Z32) Kaido-ou', 1994, 'Japonia', 'Street Tier 1', 'Nie', ''),
(NULL, 'Nissan', '300 ZX (Z32) Malu Edition', 1994, 'Japonia', 'Street Tier 1', 'Nie', ''),
(NULL, 'Nissan', '350Z Roadster', 2004, 'Japonia', 'Street Tier 2', 'Nie', ''),
(NULL, 'Nissan', '370Z (Z34)', 2013, 'Japonia', 'Street Tier 2', 'Nie', ''),
(NULL, 'Nissan', '370Z Nismo (Z34)', 2016, 'Japonia', 'Street Tier 2', 'Tak', 'Czarny'),
(NULL, 'Nissan', 'Fairlady Z 432 (PS30) 1970', 1970, 'Japonia', 'Street Tier 1', 'Tak', 'Niebieski'),
(NULL, 'Nissan', 'Fairlady Z 432 (PS30) Under The Stars Edition', 1970, 'Japonia', 'Street Tier 1', 'Nie', ''),
(NULL, 'Nissan', 'GT-R (R35)', 2016, 'Japonia', 'Street Tier 2', 'Nie', ''),
(NULL, 'Nissan', 'GT-R Nismo (R35)', 2020, 'Japonia', 'Street Tier 2', 'Tak', 'Czerwony'),
(NULL, 'Nissan', 'Skyline GT-R (R34)', 2002, 'Japonia', 'Street Tier 2', 'Tak', 'Fioletowy'),
(NULL, 'Nissan', 'Skyline GT-R (R34) High Octane Edition', 2002, 'Japonia', 'Street Tier 2', 'Nie', ''),
(NULL, 'Nissan', 'Skyline GT-R (R34) Lucky Dragon Edition', 2002, 'Japonia', 'Street Tier 2', 'Nie', ''),
(NULL, 'Nissan', 'Z', 2023, 'Japonia', 'Street Tier 2', 'Nie', ''),
(NULL, 'Plymouth', 'Road Runner', 1970, 'USA', 'Street Tier 1', 'Nie', ''),
(NULL, 'Plymouth', 'Road Runner Freedom Edition', 1970, 'USA', 'Street Tier 1', 'Nie', ''),
(NULL, 'Plymouth', 'Road Runner Lowrider', 1970, 'USA', 'Street Tier 1', 'Nie', ''),
(NULL, 'Pontiac', 'Firebird T/A Golden Wing Edition', 1977, 'USA', 'Street Tier 1', 'Nie', ''),
(NULL, 'Pontiac', 'Firebird T/A', 1977, 'USA', 'Street Tier 1', 'Nie', ''),
(NULL, 'Pontiac', 'Firebird T/A', 1982, 'USA', 'Street Tier 1', 'Tak', 'Czarny'),
(NULL, 'Pontiac', 'GTO', 1966, 'USA', 'Street Tier 1', 'Nie', ''),
(NULL, 'Pontiac', 'GTO The Judge', 1969, 'USA', 'Street Tier 1', 'Nie', ''),
(NULL, 'Porsche', '550 Spyder', 1955, 'Niemcy', 'Street Tier 1', 'Nie', ''),
(NULL, 'Porsche', '718 Spyder', 2021, 'Niemcy', 'Street Tier 2', 'Nie', ''),
(NULL, 'Porsche', '718 Spyder Keola Rapozo Edition', 2021, 'Niemcy', 'Street Tier 2', 'Nie', ''),
(NULL, 'Porsche', '911 (901)', 1964, 'Niemcy', 'Street Tier 1', 'Tak', 'Żółty'),
(NULL, 'Porsche', '911 (992) Carrera 4S', 2020, 'Niemcy', 'Street Tier 2', 'Nie', ''),
(NULL, 'Porsche', '911 (992) Carrera 4S Timeless Edition', 2020, 'Niemcy', 'Street Tier 2', 'Tak', 'Żółty'),
(NULL, 'Porsche', '911 (993) GT', 1996, 'Niemcy', 'Street Tier 2', 'Tak', 'Zielony'),
(NULL, 'Porsche', '911 GT3 RS', 2016, 'Niemcy', 'Street Tier 2', 'Tak', 'Czerwony'),
(NULL, 'Porsche', '911 GT3 RS Splatter Edition', 2016, 'Niemcy', 'Street Tier 2', 'Nie', ''),
(NULL, 'Porsche', '911 Speedster', 2019, 'Niemcy', 'Street Tier 2', 'Nie', ''),
(NULL, 'Porsche', '911 Speedster Winter Agent Edition', 2019, 'Niemcy', 'Street Tier 2', 'Nie', ''),
(NULL, 'Porsche', '911 Turbo', 1993, 'Niemcy', 'Street Tier 2', 'Tak', 'Niebieski'),
(NULL, 'Porsche', '928 S4', 1991, 'Niemcy', 'Street Tier 2', 'Nie', ''),
(NULL, 'Porsche', 'Cayenne Turbo GT (coupé)', 2022, 'Niemcy', 'Street Tier 2', 'Nie', ''),
(NULL, 'Porsche', 'Cayman GT4', 2016, 'Niemcy', 'Street Tier 2', 'Nie', ''),
(NULL, 'Porsche', 'Cayman GT4 Carbon Edition', 2016, 'Niemcy', 'Street Tier 2', 'Nie', ''),
(NULL, 'Porsche', 'Cayman GT4 Wasp Edition', 2016, 'Niemcy', 'Street Tier 2', 'Nie', ''),
(NULL, 'Porsche', 'Panamera Turbo S Sport Turismo', 2022, 'Niemcy', 'Street Tier 2', 'Nie', ''),
(NULL, 'Porsche', 'Taycan Turbo S', 2021, 'Niemcy', 'Street Tier 2', 'Tak', 'Biały'),
(NULL, 'PROTO', 'Hotrod A1', 1930, 'USA', 'Street Tier 1', 'Nie', ''),
(NULL, 'PROTO', 'Hotrod A1 Burning Wheels Edition', 1930, 'USA', 'Street Tier 1', 'Nie', ''),
(NULL, 'PROTO', 'Hotrod A1 Clumsy Edition', 1930, 'USA', 'Street Tier 1', 'Nie', ''),
(NULL, 'PROTO', 'Hotrod A1 Marco_s Cab', 1930, 'USA', 'Street Tier 1', 'Nie', ''),
(NULL, 'Renault', 'New Megane R.S.', 2018, 'Francja', 'Street Tier 1', 'Tak', 'Zielony'),
(NULL, 'Saleen', 'S1', 2020, 'USA', 'Street Tier 2', 'Tak', 'Czerwony'),
(NULL, 'Saleen', 'S1 Icebreaker', 2020, 'USA', 'Street Tier 2', 'Nie', ''),
(NULL, 'Shelby', 'Cobra 427', 1964, 'USA', 'Street Tier 1', 'Tak', 'Niebieski'),
(NULL, 'Shelby', 'GT50', 1967, 'USA', 'Street Tier 1', 'Nie', ''),
(NULL, 'Spyker', 'C8 Aileron', 2008, 'Holandia', 'Street Tier 2', 'Tak', 'Fioletowy'),
(NULL, 'Spyker', 'C8 Aileron All In Edition', 2008, 'Holandia', 'Street Tier 2', 'Nie', ''),
(NULL, 'Toyota', 'GR Supra (J29/DB)', 2021, 'Japonia', 'Street Tier 2', 'Nie', ''),
(NULL, 'Toyota', 'GR Supra (J29/DB) Liberty Walk Edition', 2021, 'Japonia', 'Street Tier 2', 'Tak', 'Czarny'),
(NULL, 'Toyota', 'Supra (A80)', 2000, 'Japonia', 'Street Tier 2', 'Tak', 'Różowy'),
(NULL, 'Toyota', 'Supra (A80) Ryūjin Edition', 2000, 'Japonia', 'Street Tier 2', 'Tak', 'Srebrny'),
(NULL, 'TVR', 'Griffith 2017', 2017, 'Wielka Brytania', 'Street Tier 2', 'Nie', ''),
(NULL, 'TVR', 'Griffith Peppermint Edition', 2017, 'Wielka Brytania', 'Street Tier 2', 'Nie', ''),
(NULL, 'TVR', 'Sagaris', 2004, 'Wielka Brytania', 'Street Tier 2', 'Nie', ''),
(NULL, 'Volkswagen', 'Beetle', 1967, 'Niemcy', 'Street Tier 1', 'Nie', ''),
(NULL, 'Volkswagen', 'Beetle Kahakai Edition', 1967, 'Niemcy', 'Street Tier 1', 'Nie', ''),
(NULL, 'Volkswagen', 'Golf GTI (A7)', 2014, 'Niemcy', 'Street Tier 1', 'Nie', ''),
(NULL, 'Volkswagen', 'Kombi 21 Window Bus', 1966, 'Niemcy', 'Street Tier 1', 'Tak', 'Niebieski'),
(NULL, 'Volkswagen', 'Kombi 21 Window Bus DAK1NE Edition', 1966, 'Niemcy', 'Street Tier 1', 'Nie', ''),
(NULL, 'Volkswagen', 'Kombi 21 Window Bus Ghost Hunt Edition', 1966, 'Niemcy', 'Street Tier 1', 'Nie', ''),
(NULL, 'Volkswagen', 'Touareg NF 2011', 2011, 'Niemcy', 'Street Tier 1', 'Nie', ''),
(NULL, 'BMW Motorrad', 'R1200GS Adventure', 2014, 'Niemcy', 'Street Tier 1', 'Nie', ''),
(NULL, 'BMW Motorrad', 'S1000RR', 2015, 'Niemcy', 'Street Tier 2', 'Nie', ''),
(NULL, 'Ducati', 'Diavel', 2015, 'Włochy', 'Street Tier 2', 'Nie', ''),
(NULL, 'Ducati', 'draXter', 2016, 'Włochy', 'Street Tier 2', 'Nie', ''),
(NULL, 'Ducati', 'Hypermotard', 2015, 'Włochy', 'Street Tier 1', 'Nie', ''),
(NULL, 'Ducati', 'Monster 1200 S', 2015, 'Włochy', 'Street Tier 2', 'Nie', ''),
(NULL, 'Ducati', 'Panigale R', 2015, 'Włochy', 'Street Tier 2', 'Nie', ''),
(NULL, 'Harley Davidson', 'Street Glide Special', 2017, 'USA', 'Street Tier 1', 'Nie', ''),
(NULL, 'Harley Davidson', 'Iron 883', 2017, 'USA', 'Street Tier 1', 'Tak', 'Czarny'),
(NULL, 'Honda', 'CBR1000RR Fireblade SP2', 2018, 'Japonia', 'Street Tier 2', 'Tak', 'Czerwony'),
(NULL, 'Honda', 'CB1000R 2018 Neo-Sports Café', 2018, 'Japonia', 'Street Tier 2', 'Tak', 'Czerwony'),
(NULL, 'Indian Motorcycle', 'Chief Dark Horse', 2015, 'USA', 'Street Tier 1', 'Nie', ''),
(NULL, 'Indian Motorcycle', 'Scout 2015', 2015, 'USA', 'Street Tier 1', 'Nie', ''),
(NULL, 'Indian Motorcycle', 'FTR 1200 S', 2019, 'USA', 'Street Tier 2', 'Nie', ''),
(NULL, 'Indian Motorcycle', 'Scout The Cruiser Edition', 2015, 'USA', 'Street Tier 1', 'Nie', ''),
(NULL, 'Kawasaki', 'GPZ 900 R Ninja', 1984, 'Japonia', 'Street Tier 2', 'Tak', 'Czerwony'),
(NULL, 'Kawasaki', 'KX450F', 2015, 'Japonia', 'Street Tier 1', 'Nie', ''),
(NULL, 'Kawasaki', 'Ninja H2', 2015, 'Japonia', 'Street Tier 2', 'Nie', ''),
(NULL, 'Kawasaki', 'Ninja H2 Light Rider Edition', 2015, 'Japonia', 'Street Tier 2', 'Nie', ''),
(NULL, 'Kawasaki', 'Z1000 ABS', 2015, 'Japonia', 'Street Tier 2', 'Tak', 'Zielony'),
(NULL, 'KTM', '450 EXC', 2015, 'Austria', 'Street Tier 1', 'Nie', ''),
(NULL, 'KTM', '1290 SUPER DUKE R ABS', 2015, 'Austria', 'Street Tier 2', 'Nie', ''),
(NULL, 'KTM', '1190 RC8 R', 2015, 'Austria', 'Street Tier 2', 'Nie', ''),
(NULL, 'Suzuki', 'GSX-R 1000R', 2018, 'Japonia', 'Street Tier 2', 'Nie', ''),
(NULL, 'Yamaha', 'VMAX 1700', 2014, 'Japonia', 'Street Tier 2', 'Tak', 'Srebrny'),
(NULL, 'Bugatti', 'Centodieci', 2019, 'Francja', 'Hypercar', 'Tak', 'Żółty'),
(NULL, 'Bugatti', 'Chiron', 2017, 'Francja', 'Hypercar', 'Tak', 'Zielony'),
(NULL, 'Bugatti', 'Chiron Carbon Edition', 2017, 'Francja', 'Hypercar', 'Nie', ''),
(NULL, 'Bugatti', 'Chiron Interception Unit', 2017, 'Francja', 'Hypercar', 'Nie', ''),
(NULL, 'Bugatti', 'Chiron Super Sport 300+', 2019, 'Francja', 'Hypercar', 'Nie', ''),
(NULL, 'Bugatti', 'EB110 Super Sport', 1992, 'Francja', 'Hypercar', 'Nie', ''),
(NULL, 'Bugatti', 'EB110 Super Sport Anodized Edition', 1992, 'Francja', 'Hypercar', 'Nie', ''),
(NULL, 'Bugatti', 'Divo', 2019, 'Francja', 'Hypercar', 'Nie', ''),
(NULL, 'Bugatti', 'Divo Magma Edition', 2019, 'Francja', 'Hypercar', 'Nie', ''),
(NULL, 'Bugatti', 'Divo Emerald Storm Edition', 2019, 'Francja', 'Hypercar', 'Nie', ''),
(NULL, 'Bugatti', 'La Voiture Noire', 2019, 'Francja', 'Hypercar', 'Nie', ''),
(NULL, 'Bugatti', 'Veyron 16.4 Grand Sport Vitesse', 2016, 'Francja', 'Hypercar', 'Nie', ''),
(NULL, 'Bugatti', 'Veyron 16.4 Grand Sport Vitesse Deep Blue Edition', 2016, 'Francja', 'Hypercar', 'Nie', ''),
(NULL, 'Bugatti', 'Veyron 16.4 Grand Sport Vitesse Edition One', 2016, 'Francja', 'Hypercar', 'Nie', ''),
(NULL, 'Bugatti', 'Veyron Barchetta', 2015, 'Francja', 'Hypercar', 'Nie', ''),
(NULL, 'Chevrolet', 'Corvette C7 ZR1', 2019, 'USA', 'Hypercar', 'Tak', 'Czerwony'),
(NULL, 'Chevrolet', 'Corvette C7 ZR1 Convertible', 2019, 'USA', 'Hypercar', 'Nie', ''),
(NULL, 'Chevrolet', 'Corvette C7 ZR1 Convertible Long Range Edition', 2019, 'USA', 'Hypercar', 'Nie', ''),
(NULL, 'Chevrolet', 'Corvette C7 ZR1 Gold Nugget Edition', 2019, 'USA', 'Hypercar', 'Nie', ''),
(NULL, 'Citroën', 'GT', 2008, 'Francja', 'Hypercar', 'Tak', 'Niebieski'),
(NULL, 'Creators', 'K.S. Masked Leader', 2020, 'Wielka Brytania', 'Hypercar', 'Nie', ''),
(NULL, 'Creators', 'Tempesta', 2022, 'Włochy', 'Hypercar', 'Nie', ''),
(NULL, 'Ferrari', '458 Speciale', 2014, 'Włochy', 'Hypercar', 'Nie', ''),
(NULL, 'Ferrari', '488 Pista', 2018, 'Włochy', 'Hypercar', 'Tak', 'Czerwony'),
(NULL, 'Ferrari', '812 Superfast', 2017, 'Włochy', 'Hypercar', 'Nie', ''),
(NULL, 'Ferrari', 'Enzo Ferrari', 2002, 'Włochy', 'Hypercar', 'Nie', ''),
(NULL, 'Ferrari', 'F12tdf', 2016, 'Włochy', 'Hypercar', 'Nie', ''),
(NULL, 'Ferrari', 'LAFERRARI', 2014, 'Włochy', 'Hypercar', 'Nie', ''),
(NULL, 'Ferrari', 'SF90 Stradale', 2020, 'Włochy', 'Hypercar', 'Nie', ''),
(NULL, 'Ford', 'GT', 2017, 'USA', 'Hypercar', 'Tak', 'Srebrny'),
(NULL, 'Ford', 'GT Interception Unit', 2017, 'USA', 'Hypercar', 'Nie', ''),
(NULL, 'Jaguar', 'C-X75 Concept', 2013, 'Wielka Brytania', 'Hypercar', 'Nie', ''),
(NULL, 'Jaguar', 'C-X75 Concept Lunar Year Edition', 2013, 'Wielka Brytania', 'Hypercar', 'Nie', ''),
(NULL, 'Koenigsegg', 'Agera R', 2012, 'Szwecja', 'Hypercar', 'Nie', ''),
(NULL, 'Koenigsegg', 'CCR', 2004, 'Szwecja', 'Hypercar', 'Nie', ''),
(NULL, 'Koenigsegg', 'Gemera', 2020, 'Szwecja', 'Hypercar', 'Nie', ''),
(NULL, 'Koenigsegg', 'Gemera Outclassed Edition', 2020, 'Szwecja', 'Hypercar', 'Nie', ''),
(NULL, 'Koenigsegg', 'Jesko', 2020, 'Szwecja', 'Hypercar', 'Nie', ''),
(NULL, 'Koenigsegg', 'One:1', 2014, 'Szwecja', 'Hypercar', 'Nie', ''),
(NULL, 'Koenigsegg', 'Regera', 2015, 'Szwecja', 'Hypercar', 'Nie', ''),
(NULL, 'KTM', 'X-Bow GTX', 2020, 'Austria', 'Hypercar', 'Nie', ''),
(NULL, 'Lamborghini', 'Aventador LP 700-4', 2012, 'Włochy', 'Hypercar', 'Nie', ''),
(NULL, 'Lamborghini', 'Countach LPI 800-4', 2021, 'Włochy', 'Hypercar', 'Nie', ''),
(NULL, 'Lamborghini', 'Egoista', 2013, 'Włochy', 'Hypercar', 'Tak', 'Srebrny'),
(NULL, 'Lamborghini', 'Huracan Performante', 2018, 'Włochy', 'Hypercar', 'Nie', ''),
(NULL, 'Lamborghini', 'Reventon', 2007, 'Włochy', 'Hypercar', 'Nie', ''),
(NULL, 'Lamborghini', 'Revuelto', 2023, 'Włochy', 'Hypercar', 'Tak', 'Czarny'),
(NULL, 'Lamborghini', 'Sián Roadster', 2020, 'Włochy', 'Hypercar', 'Nie', ''),
(NULL, 'Lamborghini', 'Terzo Millennio', 2017, 'Włochy', 'Hypercar', 'Nie', ''),
(NULL, 'Lamborghini', 'Veneno coupé (2013)', 2013, 'Włochy', 'Hypercar', 'Nie', ''),
(NULL, 'Lamborghini', 'Veneno coupé (2013) Interception Unit', 2013, 'Włochy', 'Hypercar', 'Nie', ''),
(NULL, 'Lotus', 'Evija', 2022, 'Wielka Brytania', 'Hypercar', 'Nie', ''),
(NULL, 'Lotus', 'Evija Pure Edition', 2022, 'Wielka Brytania', 'Hypercar', 'Tak', 'Fioletowy'),
(NULL, 'Maserati', 'Alfieri', 2014, 'Włochy', 'Hypercar', 'Nie', ''),
(NULL, 'Maserati', 'MC12', 2004, 'Włochy', 'Hypercar', 'Tak', 'Czerwony'),
(NULL, 'Maserati', 'MC20', 2021, 'Włochy', 'Hypercar', 'Nie', ''),
(NULL, 'McLaren', '12C', 2013, 'Wielka Brytania', 'Hypercar', 'Nie', ''),
(NULL, 'McLaren', '720S Spider', 2019, 'Wielka Brytania', 'Hypercar', 'Nie', ''),
(NULL, 'McLaren', '720S Spider Blast Edition', 2019, 'Wielka Brytania', 'Hypercar', 'Nie', ''),
(NULL, 'McLaren', '765LT', 2020, 'Wielka Brytania', 'Hypercar', 'Nie', ''),
(NULL, 'McLaren', 'Elva', 2021, 'Wielka Brytania', 'Hypercar', 'Tak', 'Czarny'),
(NULL, 'McLaren', 'F1', 1993, 'Wielka Brytania', 'Hypercar', 'Tak', 'Pomarańczowy'),
(NULL, 'McLaren', 'P1', 2013, 'Wielka Brytania', 'Hypercar', 'Tak', 'Zielony'),
(NULL, 'McLaren', 'P1 Gold Line Edition', 2013, 'Wielka Brytania', 'Hypercar', 'Nie', ''),
(NULL, 'McLaren', 'Senna', 2018, 'Wielka Brytania', 'Hypercar', 'Nie', ''),
(NULL, 'Mercedes-Benz', 'Vision EQ Silver Arrow', 2018, 'Niemcy', 'Hypercar', 'Tak', 'Srebrny'),
(NULL, 'Nissan', 'R390 GT1 Road Version', 1998, 'Japonia', 'Hypercar', 'Nie', ''),
(NULL, 'Pagani', 'Huayra', 2012, 'Włochy', 'Hypercar', 'Nie', ''),
(NULL, 'Pagani', 'Huayra Rubicone Edizione', 2012, 'Włochy', 'Hypercar', 'Tak', 'Biały'),
(NULL, 'Pagani', 'Zonda F', 2005, 'Włochy', 'Hypercar', 'Nie', ''),
(NULL, 'Pagani', 'Zonda F Primary Edition', 2005, 'Włochy', 'Hypercar', 'Nie', ''),
(NULL, 'Porsche', '911 GT1 Straβenversion (993)', 1996, 'Niemcy', 'Hypercar', 'Tak', 'Pomarańczowy'),
(NULL, 'Porsche', '918 Spyder', 2015, 'Niemcy', 'Hypercar', 'Tak', 'Srebrny'),
(NULL, 'Porsche', '918 Spyder Silvery Edition', 2015, 'Niemcy', 'Hypercar', 'Nie', ''),
(NULL, 'Porsche', 'Carrera GT', 2003, 'Niemcy', 'Hypercar', 'Nie', ''),
(NULL, 'Porsche', 'Carrera GT Green Flash Edition', 2003, 'Niemcy', 'Hypercar', 'Nie', ''),
(NULL, 'PROTO (unlicensed)', 'Lucky-One', 2022, 'Francja', 'Hypercar', 'Nie', ''),
(NULL, 'Renault', 'TreZor', 2016, 'Francja', 'Hypercar', 'Nie', ''),
(NULL, 'Saleen', 'S7 Twin-Turbo', 2005, 'USA', 'Hypercar', 'Nie', ''),
(NULL, 'Saleen', 'S7 Twin-Turbo Glacier Edition', 2005, 'USA', 'Hypercar', 'Nie', ''),
(NULL, 'Acura', 'NSX 2017 (U.S. Spec)', 2017, 'USA', 'Drift', 'Nie', ''),
(NULL, 'BMW', 'M5 (F10)', 2011, 'Niemcy', 'Drift', 'Nie', ''),
(NULL, 'BMW', 'Z4 sDrive35is (E89)', 2011, 'Niemcy', 'Drift', 'Nie', ''),
(NULL, 'Chevrolet', 'Camaro SS', 2010, 'USA', 'Drift', 'Nie', ''),
(NULL, 'Chevrolet', 'Corvette Stingray', 2014, 'USA', 'Drift', 'Nie', ''),
(NULL, 'Creators', 'De Lorean DMC-12 Outadrift', 1981, 'Francja', 'Drift', 'Nie', ''),
(NULL, 'Dodge', 'Challenger SRT-8 392', 2012, 'USA', 'Drift', 'Nie', ''),
(NULL, 'Dodge', 'Charger R/T Hemi', 1969, 'USA', 'Drift', 'Nie', ''),
(NULL, 'Dodge', 'SRT Viper GTS', 2013, 'USA', 'Drift', 'Nie', ''),
(NULL, 'Ferrari', '458 Speciale', 2014, 'Włochy', 'Drift', 'Nie', ''),
(NULL, 'Ford', 'Crown Victoria Limousine', 2008, 'USA', 'Drift', 'Nie', ''),
(NULL, 'Ford', 'Focus RS', 2010, 'USA', 'Drift', 'Nie', ''),
(NULL, 'Ford', 'GT', 2005, 'USA', 'Drift', 'Nie', ''),
(NULL, 'Ford', 'Mustang GT', 2011, 'USA', 'Drift', 'Nie', ''),
(NULL, 'Ford', 'Mustang GT Fastback', 2015, 'USA', 'Drift', 'Nie', ''),
(NULL, 'Forsberg Racing', 'Nissan 350Z Roadster', 2009, 'Japonia', 'Drift', 'Nie', ''),
(NULL, 'Forsberg Racing', 'Nissan 370Z PRO DRIFT', 2021, 'Japonia', 'Drift', 'Tak', 'Pomarańczowy'),
(NULL, 'Koenigsegg', 'Agera R', 2012, 'Szwecja', 'Drift', 'Nie', ''),
(NULL, 'Lamborghini', 'Aventador LP 700-4', 2012, 'Włochy', 'Drift', 'Nie', ''),
(NULL, 'Lamborghini', 'Murciélago LP640', 2006, 'Włochy', 'Drift', 'Nie', ''),
(NULL, 'Mazda', 'RX7 2002', 2002, 'Japonia', 'Drift', 'Tak', 'Srebrny'),
(NULL, 'McLaren', '12C', 2013, 'Wielka Brytania', 'Drift', 'Nie', ''),
(NULL, 'Mitsubishi', 'Lancer Evolution X Drift Edition', 2014, 'Japonia', 'Drift', 'Tak', 'Pomarańczowy'),
(NULL, 'Nissan', '370Z (Z34)', 2013, 'Japonia', 'Drift', 'Tak', 'Fioletowy'),
(NULL, 'Nissan', '370Z Nismo (Z34)', 2016, 'Japonia', 'Drift', 'Tak', 'Błękitny'),
(NULL, 'Nissan', 'Skyline GT-R (R34)', 2002, 'Japonia', 'Drift', 'Tak', 'Czarny'),
(NULL, 'RUF', '3400 K', 2007, 'Niemcy', 'Drift', 'Nie', ''),
(NULL, 'RUF', 'CTR 3', 2007, 'Niemcy', 'Drift', 'Nie', ''),
(NULL, 'Shelby', 'GT500', 1967, 'USA', 'Drift', 'Nie', ''),
(NULL, 'Toyota', 'GR Supra (J29/DB) Drift Edition', 2021, 'Japonia', 'Drift', 'Tak', 'Żółty'),
(NULL, 'Chevrolet', 'Camaro SS', 2010, 'USA', 'Dragster', 'Tak', 'Żółty'),
(NULL, 'Chevrolet', 'Corvette Stingray', 2014, 'USA', 'Dragster', 'Tak', 'Niebieski'),
(NULL, 'Dodge', 'Challenger SRT-8 392', 2012, 'USA', 'Dragster', 'Nie', ''),
(NULL, 'Dodge', 'SRT Viper GTS 2013', 2013, 'USA', 'Dragster', 'Nie', ''),
(NULL, 'Ford', 'Focus RS', 2010, 'USA', 'Dragster', 'Nie', ''),
(NULL, 'Ford', 'Mustang GT', 2011, 'USA', 'Dragster', 'Nie', ''),
(NULL, 'Nissan', '370Z (Z34)', 2013, 'Japonia', 'Dragster', 'Nie', ''),
(NULL, 'Nissan', 'Skyline GT-R (R34)', 2002, 'Japonia', 'Dragster', 'Nie', ''),
(NULL, 'PROTO', 'NSX 2017 (U.S. Spec)', 1930, 'USA', 'Dragster', 'Nie', ''),
(NULL, 'RUF', '3400 K', 2007, 'Niemcy', 'Dragster', 'Nie', ''),
(NULL, 'RUF', 'CTR 3', 2007, 'Niemcy', 'Dragster', 'Nie', ''),
(NULL, 'Acura', 'NSX GT3 (U.S. Spec)', 2017, 'USA', 'Racing', 'Nie', ''),
(NULL, 'Aston Martin', 'Vulcan', 2016, 'Wielka Brytania', 'Racing', 'Nie', ''),
(NULL, 'Aston Martin', 'Vulcan The Duke', 2016, 'Wielka Brytania', 'Racing', 'Nie', ''),
(NULL, 'Audi', 'RS 3 LMS', 2017, 'Niemcy', 'Racing', 'Nie', ''),
(NULL, 'Bentley', 'Continental Supersports', 2010, 'Wielka Brytania', 'Racing', 'Nie', ''),
(NULL, 'BMW', 'M Performance M4 Racing', 2014, 'Niemcy', 'Racing', 'Nie', ''),
(NULL, 'BMW', 'M6 GT3 (F13)', 2016, 'Niemcy', 'Racing', 'Nie', ''),
(NULL, 'BMW', 'Z4 GT3 (E89)', 2011, 'Niemcy', 'Racing', 'Nie', ''),
(NULL, 'Bugatti', 'Bolide', 2020, 'Francja', 'Racing', 'Tak', 'Żółty'),
(NULL, 'Cadillac', 'Escalade 2012', 2012, 'USA', 'Racing', 'Nie', ''),
(NULL, 'Chevrolet', 'Camaro RS', 1969, 'USA', 'Racing', 'Nie', ''),
(NULL, 'Chevrolet', 'Camaro SS', 2010, 'USA', 'Racing', 'Tak', 'Pomarańczowy'),
(NULL, 'Chevrolet', 'Camping World Truck Series Chevrolet Silverado', 2009, 'USA', 'Racing', 'Nie', ''),
(NULL, 'Chevrolet', 'Corvette C3', 1968, 'USA', 'Racing', 'Nie', ''),
(NULL, 'Chevrolet', 'Corvette C3 F1R3 Ed.', 1968, 'USA', 'Racing', 'Nie', ''),
(NULL, 'Chevrolet', 'Corvette C6R', 2005, 'USA', 'Racing', 'Tak', 'Niebieski'),
(NULL, 'Chevrolet', 'Corvette C8.R (Race Car)', 2020, 'USA', 'Racing', 'Nie', ''),
(NULL, 'Chevrolet', 'Impala Sport Sedan', 1967, 'USA', 'Racing', 'Nie', ''),
(NULL, 'Dodge', 'Challenger SRT-8 392', 2012, 'USA', 'Racing', 'Nie', ''),
(NULL, 'Dodge', 'Charger R/T Hemi', 1969, 'USA', 'Racing', 'Nie', ''),
(NULL, 'Dodge', 'Charger SRT-8 ', 2012, 'USA', 'Racing', 'Nie', ''),
(NULL, 'Dodge', 'Viper Competition Coupe', 2003, 'USA', 'Racing', 'Tak', 'Czerwony'),
(NULL, 'Ferrari', '365 GTB/4 Competizione (Daytona)', 1971, 'Włochy', 'Racing', 'Tak', 'Żółty'),
(NULL, 'Ferrari', '458 Italia GT2', 2011, 'Włochy', 'Racing', 'Nie', ''),
(NULL, 'Ferrari', '488 GT3', 2016, 'Włochy', 'Racing', 'Tak', 'Zielony'),
(NULL, 'Ferrari', '599XX Evo', 2011, 'Włochy', 'Racing', 'Nie', ''),
(NULL, 'Ferrari', 'F40 LM', 1989, 'Włochy', 'Racing', 'Nie', ''),
(NULL, 'Ferrari', 'FXX K', 2014, 'Włochy', 'Racing', 'Nie', ''),
(NULL, 'Ford', 'F-150 SVT Raptor', 2010, 'USA', 'Racing', 'Nie', ''),
(NULL, 'Ford', 'Focus RS', 2010, 'USA', 'Racing', 'Nie', ''),
(NULL, 'Ford', 'GT', 2005, 'USA', 'Racing', 'Tak', 'Błękitny'),
(NULL, 'Ford', 'GT Le Mans Race Car', 2017, 'USA', 'Racing', 'Tak', 'Niebieski'),
(NULL, 'Ford', 'GT [Le Mans Race Car] - Airfoil Edition', 2017, 'USA', 'Racing', 'Tak', 'Żółty'),
(NULL, 'Ford', 'Mustang GT', 2011, 'USA', 'Racing', 'Nie', ''),
(NULL, 'Forsberg Racing', 'Nissan GT-R Nismo GT3', 2020, 'Japonia', 'Racing', 'Nie', ''),
(NULL, 'Koenigsegg', 'CCGT', 2007, 'Szwecja', 'Racing', 'Tak', 'Niebieski'),
(NULL, 'KTM', 'X-Bow GT2', 2020, 'Austria', 'Racing', 'Nie', ''),
(NULL, 'KTM', 'X-Bow GT4', 2016, 'Austria', 'Racing', 'Nie', ''),
(NULL, 'KTM', 'X-Bow GT4 Raw Edition', 2016, 'Austria', 'Racing', 'Nie', ''),
(NULL, 'Lamborghini', 'Essenza SCV12', 2020, 'Włochy', 'Racing', 'Tak', 'Zielony'),
(NULL, 'Lamborghini', 'Gallardo LP 570-4 Super Trofeo', 2013, 'Włochy', 'Racing', 'Nie', ''),
(NULL, 'Lamborghini', 'Huracan LP620-2 Super Trofeo', 2015, 'Włochy', 'Racing', 'Nie', ''),
(NULL, 'Lamborghini', 'Murciélago RGT', 2003, 'Włochy', 'Racing', 'Nie', ''),
(NULL, 'Maserati', 'GranTurismo S', 2009, 'Włochy', 'Racing', 'Nie', ''),
(NULL, 'Maserati', 'MC12 versione Corse', 2006, 'Włochy', 'Racing', 'Nie', ''),
(NULL, 'Mazda', 'MX5 (ND)', 2016, 'Japonia', 'Racing', 'Nie', ''),
(NULL, 'McLaren', '12C GT3', 2014, 'Wielka Brytania', 'Racing', 'Nie', ''),
(NULL, 'McLaren', 'Senna GTR', 2020, 'Wielka Brytania', 'Racing', 'Nie', ''),
(NULL, 'Mercedes-AMG', 'C 63 Touring Car (C-Coupé DTM)', 2016, 'Niemcy', 'Racing', 'Nie', ''),
(NULL, 'Mercedes-AMG', 'C-Coupé Touring Car (DTM)', 2012, 'Niemcy', 'Racing', 'Nie', ''),
(NULL, 'Mercedes-AMG', 'GT3', 2015, 'Niemcy', 'Racing', 'Tak', 'Biały'),
(NULL, 'Mercedes-AMG', 'SL 63 (R230)', 2009, 'Niemcy', 'Racing', 'Nie', ''),
(NULL, 'Mercedes-AMG', 'SLS GT3', 2011, 'Niemcy', 'Racing', 'Nie', ''),
(NULL, 'Mercedes-Benz', '300 SLR UHLENHAUT COUPE (W196)', 1955, 'Niemcy', 'Racing', 'Nie', ''),
(NULL, 'Mercedes-Benz', 'SLR McLaren 722 GT', 2007, 'Niemcy', 'Racing', 'Nie', ''),
(NULL, 'Mini', 'Cooper S (R56)', 2010, 'Wielka Brytania', 'Racing', 'Tak', 'Czarny'),
(NULL, 'Mini', 'Cooper S (R56) Checkered Edition', 2010, 'Wielka Brytania', 'Racing', 'Nie', ''),
(NULL, 'Nissan', '370Z (Z34) Racing', 2013, 'Japonia', 'Racing', 'Nie', ''),
(NULL, 'Nissan', 'GT-R Nismo GT3', 2018, 'Japonia', 'Racing', 'Nie', ''),
(NULL, 'Nissan', 'Skyline GT-R (R34) Racing', 2002, 'Japonia', 'Racing', 'Nie', ''),
(NULL, 'Pagani', 'Zonda R', 2008, 'Włochy', 'Racing', 'Nie', ''),
(NULL, 'Porsche', '911 Carrera RSR Turbo', 1974, 'Niemcy', 'Racing', 'Nie', ''),
(NULL, 'Porsche', '911 Carrera RSR Turbo Pulse Performance Ed.', 1974, 'Niemcy', 'Racing', 'Nie', ''),
(NULL, 'Porsche', '911 GT3 Cup', 2017, 'Niemcy', 'Racing', 'Nie', ''),
(NULL, 'Porsche', '917K 1970', 1970, 'Niemcy', 'Racing', 'Nie', ''),
(NULL, 'Porsche', '935 2.0 Coupé Baby', 1977, 'Niemcy', 'Racing', 'Nie', ''),
(NULL, 'Porsche', '935 2.0 Coupé Baby Old-Timer Edition', 1977, 'Niemcy', 'Racing', 'Nie', ''),
(NULL, 'PROTO', 'Hotrod A1', 1930, 'USA', 'Racing', 'Nie', ''),
(NULL, 'Renault', 'R.S.01', 2016, 'Francja', 'Racing', 'Tak', 'Błękitny'),
(NULL, 'Saleen', 'S1 GT4 Cup', 2020, 'USA', 'Racing', 'Tak', 'Żółty'),
(NULL, 'Saleen', 'S7R', 2000, 'USA', 'Racing', 'Nie', ''),
(NULL, 'Shelby', 'GT500', 1967, 'USA', 'Racing', 'Nie', ''),
(NULL, 'Spyker', 'C8 LaViolette GT2-R', 2008, 'Holandia', 'Racing', 'Nie', ''),
(NULL, 'BMW Motorrad', 'S1000RR', 2015, 'Niemcy', 'Racing', 'Nie', ''),
(NULL, 'Ducati', 'Panigale R 2015', 2015, 'Włochy', 'Racing', 'Nie', ''),
(NULL, 'Kawasaki', 'GPZ 900 R Ninja', 1984, 'Japonia', 'Racing', 'Nie', ''),
(NULL, 'Kawasaki', 'Ninja H2', 2015, 'Japonia', 'Racing', 'Nie', ''),
(NULL, 'Kawasaki', 'Z1000 ABS', 2015, 'Japonia', 'Racing', 'Nie', ''),
(NULL, 'KTM', '1190 RC8 R Track', 2015, 'Austria', 'Racing', 'Nie', ''),
(NULL, 'KTM', '1190 RC8 R Track 2015 Power Track Edition', 2015, 'Austria', 'Racing', 'Nie', ''),
(NULL, 'KTM', 'RC16 - Red Bull Team', 2022, 'Austria', 'Racing', 'Tak', 'Granatowy'),
(NULL, 'KTM', 'RC16 - Tech 3 Team', 2022, 'Austria', 'Racing', 'Nie', ''),
(NULL, 'Suzuki', 'GSX-RR 2016 - Team Suzuki Ecstar', 2016, 'Japonia', 'Racing', 'Tak', 'Niebieski'),
(NULL, 'Yamaha', 'YZR-M1 2016', 2016, 'Japonia', 'Racing', 'Nie', ''),
(NULL, 'Audi', 'S1 EKS RX quattro', 2017, 'Niemcy', 'Rally', 'Nie', ''),
(NULL, 'Cadillac', 'Escalade Enforcer Edition', 2012, 'USA', 'Rally', 'Nie', ''),
(NULL, 'Chevrolet', 'Camaro RS', 1969, 'USA', 'Rally', 'Nie', ''),
(NULL, 'Chevrolet', 'Camaro SS', 2010, 'USA', 'Rally', 'Tak', 'Różowy'),
(NULL, 'Chevrolet', 'Camaro Z/28 RS Enforcer Edition', 1971, 'USA', 'Rally', 'Nie', ''),
(NULL, 'Citroën', 'C3 Racing 2017', 2017, 'Francja', 'Rally', 'Tak', 'Niebieski'),
(NULL, 'Creators', 'Tkachenko Ice Hunter', 2021, 'Rosja', 'Rally', 'Nie', ''),
(NULL, 'Dodge', 'Challenger SRT-8 392', 2012, 'USA', 'Rally', 'Tak', 'Czerwony'),
(NULL, 'Dodge', 'Charger R/T Hemi', 1969, 'USA', 'Rally', 'Nie', ''),
(NULL, 'Dodge', 'Charger SRT-8 ', 2012, 'USA', 'Rally', 'Nie', ''),
(NULL, 'Ford', 'FIESTA WRC', 2017, 'USA', 'Rally', 'Tak', 'Czerwony'),
(NULL, 'Ford', 'Focus RS', 2010, 'USA', 'Rally', 'Tak', 'Zielony'),
(NULL, 'Ford', 'Focus RSRX', 2016, 'USA', 'Rally', 'Nie', ''),
(NULL, 'Ford', 'Focus RSRX Glow Motorsport Ed.', 2016, 'USA', 'Rally', 'Nie', ''),
(NULL, 'Ford', 'Mustang GT', 2011, 'USA', 'Rally', 'Nie', ''),
(NULL, 'Forsberg Racing', 'Nissan 370Z East African Safari Z', 2020, 'Japonia', 'Rally', 'Nie', ''),
(NULL, 'Lotus', 'Exige S', 2013, 'Wielka Brytania', 'Rally', 'Nie', ''),
(NULL, 'Mini', 'Cooper S (R56)', 2010, 'Wielka Brytania', 'Rally', 'Nie', ''),
(NULL, 'Mini', 'Cooper S Countryman ALL4 (R60)', 2013, 'Wielka Brytania', 'Rally', 'Nie', ''),
(NULL, 'Mitsubishi', 'Lancer WRC05', 2005, 'Japonia', 'Rally', 'Nie', ''),
(NULL, 'Nissan', '370Z (Z34)', 2013, 'Japonia', 'Rally', 'Nie', ''),
(NULL, 'Nissan', 'Fairlady Z 432 (PS30)', 1970, 'Japonia', 'Rally', 'Tak', 'Biały'),
(NULL, 'Nissan', 'Skyline GT-R (R34)', 2002, 'Japonia', 'Rally', 'Nie', ''),
(NULL, 'Porsche', '911 GT3 RS RD Limited Edition', 2016, 'Niemcy', 'Rally', 'Nie', ''),
(NULL, 'Shelby', 'GT500 Americar Edition', 1967, 'USA', 'Rally', 'Nie', ''),
(NULL, 'Ariel', 'Nomad', 2015, 'Wielka Brytania', 'Rally Raid', 'Nie', ''),
(NULL, 'BMW', 'Z4 sDrive35is (E89)', 2011, 'Niemcy', 'Rally Raid', 'Nie', ''),
(NULL, 'Cadillac', 'Escalade', 2012, 'USA', 'Rally Raid', 'Nie', ''),
(NULL, 'Chevrolet', 'Camaro RS 1969', 1969, 'USA', 'Rally Raid', 'Nie', ''),
(NULL, 'Chevrolet', 'Camaro SS 2010', 2010, 'USA', 'Rally Raid', 'Tak', 'Zielony'),
(NULL, 'Chevrolet', 'Silverado 1500 2010 Rally Raid Evo1', 2010, 'USA', 'Rally Raid', 'Nie', ''),
(NULL, 'Chevrolet', 'Silverado 1500 2010 Rally Raid Evo2', 2010, 'USA', 'Rally Raid', 'Nie', ''),
(NULL, 'Chevrolet', 'Silverado 1500 Intrepid Outdoors', 2010, 'USA', 'Rally Raid', 'Nie', ''),
(NULL, 'Creators', 'Hunter 51', 2021, 'USA', 'Rally Raid', 'Nie', ''),
(NULL, 'Dodge', 'Challenger SRT-8 392', 2012, 'USA', 'Rally Raid', 'Nie', ''),
(NULL, 'Ford', 'Bronco', 2021, 'USA', 'Rally Raid', 'Nie', ''),
(NULL, 'Ford', 'Bronco Hawaii Scenic Tour Ed.', 2021, 'USA', 'Rally Raid', 'Tak', 'Błękitny'),
(NULL, 'Ford', 'F-150 Raptor Race Truck 2017', 2017, 'USA', 'Rally Raid', 'Nie', ''),
(NULL, 'Ford', 'F-150 Raptor Race Truck - Ghost Recon Edition', 2017, 'USA', 'Rally Raid', 'Nie', ''),
(NULL, 'Ford', 'F-150 SVT Raptor', 2010, 'USA', 'Rally Raid', 'Nie', ''),
(NULL, 'Ford', 'F-150 SVT Raptor 2010 Enforcer Edition', 2010, 'USA', 'Rally Raid', 'Nie', ''),
(NULL, 'Ford', 'F-150 SVT Raptor 2010 from Outer Space', 2010, 'USA', 'Rally Raid', 'Nie', ''),
(NULL, 'Ford', 'Focus RS', 2010, 'USA', 'Rally Raid', 'Tak', 'Czerwony'),
(NULL, 'Ford', 'Mustang GT', 2011, 'USA', 'Rally Raid', 'Tak', 'Zielony'),
(NULL, 'GMC', 'Hummer EV', 2022, 'USA', 'Rally Raid', 'Tak', 'Żółty'),
(NULL, 'Hummer', 'H1 Alpha Rally Raid Evo1', 2006, 'USA', 'Rally Raid', 'Nie', ''),
(NULL, 'Hummer', 'H1 Alpha Rally Raid Evo2', 2006, 'USA', 'Rally Raid', 'Nie', ''),
(NULL, 'Hummer', 'H1 Alpha US Wildlife Watchers', 2006, 'USA', 'Rally Raid', 'Nie', ''),
(NULL, 'Hummer', 'HX Concept', 2008, 'USA', 'Rally Raid', 'Nie', ''),
(NULL, 'Hummer', 'HX Concept Enforcer Edition', 2008, 'USA', 'Rally Raid', 'Nie', ''),
(NULL, 'IVORY-TOWER', 'Falcon IVT-R1000', 2023, 'Francja', 'Rally Raid', 'Tak', 'Zielony'),
(NULL, 'IVORY-TOWER', 'SSV Mk2', 2023, 'Francja', 'Rally Raid', 'Nie', ''),
(NULL, 'Jeep®', 'Grand Cherokee SRT8® 2012', 2012, 'USA', 'Rally Raid', 'Nie', ''),
(NULL, 'Jeep®', 'MOAB Quicksand Concept', 2017, 'USA', 'Rally Raid', 'Nie', ''),
(NULL, 'Jeep®', 'Wrangler - Rally Raid Evo1', 2012, 'USA', 'Rally Raid', 'Nie', ''),
(NULL, 'Jeep®', 'Wrangler - Rally Raid Evo2', 2012, 'USA', 'Rally Raid', 'Nie', ''),
(NULL, 'Jeep®', 'Wrangler Unlimited Rubicon 392', 2021, 'USA', 'Rally Raid', 'Nie', ''),
(NULL, 'Land Rover', 'Defender 90 Works V8 - Edition 02', 2018, 'Wielka Brytania', 'Rally Raid', 'Nie', ''),
(NULL, 'Land Rover', 'Defender 90 Works V8 70th Edition', 2018, 'Wielka Brytania', 'Rally Raid', 'Nie', ''),
(NULL, 'Land Rover', 'Defender 90 Works V8 Intrepid Outdoors', 2018, 'Wielka Brytania', 'Rally Raid', 'Nie', ''),
(NULL, 'Mazda', 'MX5 MIATA NA', 1989, 'Japonia', 'Rally Raid', 'Nie', ''),
(NULL, 'Mazda', 'MX5 MIATA NA Spearhog Ed.', 1989, 'Japonia', 'Rally Raid', 'Nie', ''),
(NULL, 'Mercedes-Benz', 'X-Class', 2017, 'Niemcy', 'Rally Raid', 'Nie', ''),
(NULL, 'Mini', 'Countryman ALL4 Racing', 2013, 'Wielka Brytania', 'Rally Raid', 'Nie', ''),
(NULL, 'Nissan', '370Z (Z34)', 2013, 'Japonia', 'Rally Raid', 'Nie', ''),
(NULL, 'Nissan', 'Skyline GT-R (R34)', 2002, 'Japonia', 'Rally Raid', 'Nie', ''),
(NULL, 'Peugeot', '3008 DKR Maxi', 2018, 'Francja', 'Rally Raid', 'Nie', ''),
(NULL, 'Pontiac', 'GTO The Judge', 1969, 'USA', 'Rally Raid', 'Nie', ''),
(NULL, 'Pontiac', 'GTO The Judge Sparrow Competition Ed.', 1969, 'USA', 'Rally Raid', 'Nie', ''),
(NULL, 'Porsche', '959 Raid', 1985, 'Niemcy', 'Rally Raid', 'Tak', 'Błękitny'),
(NULL, 'PROTO', 'Buggy A1', 2017, 'USA', 'Rally Raid', 'Nie', ''),
(NULL, 'Ram', '1500 Rebel TRX Concept', 2017, 'USA', 'Rally Raid', 'Nie', ''),
(NULL, 'Ram', '1500 Rebel TRX Concept Enforcer Edition', 2017, 'USA', 'Rally Raid', 'Nie', ''),
(NULL, 'RUF', '3400 K', 2007, 'Niemcy', 'Rally Raid', 'Nie', ''),
(NULL, 'Toyota', 'Tacoma', 2021, 'Japonia', 'Rally Raid', 'Nie', ''),
(NULL, 'Volkswagen', 'Beetle', 1967, 'Niemcy', 'Rally Raid', 'Nie', ''),
(NULL, 'Volkswagen', 'Beetle Hoodlum Racing Crew Ed.', 1967, 'Niemcy', 'Rally Raid', 'Nie', ''),
(NULL, 'Volkswagen', 'ID Buggy', 2019, 'Niemcy', 'Rally Raid', 'Tak', 'Zielony'),
(NULL, 'Volkswagen', 'Race Touareg 3', 2011, 'Niemcy', 'Rally Raid', 'Nie', ''),
(NULL, 'BMW Motorrad', 'R1200GS Adventure', 2014, 'Niemcy', 'Rally Raid', 'Nie', ''),
(NULL, 'Ducati', 'Hypermotard', 2015, 'Włochy', 'Rally Raid', 'Nie', ''),
(NULL, 'Ducati', 'Monster 1200 S', 2015, 'Włochy', 'Rally Raid', 'Nie', ''),
(NULL, 'Kawasaki', 'KX450F', 2015, 'Japonia', 'Rally Raid', 'Tak', 'Zielony'),
(NULL, 'KTM', '450 Rally', 2015, 'Austria', 'Rally Raid', 'Nie', ''),
(NULL, 'KTM', '525 XC (Race Spec)', 2011, 'Austria', 'Rally Raid', 'Tak', 'Pomarańczowy'),
(NULL, 'Kawasaki', 'KX450F', 2015, 'Japonia', 'Motorcross', 'Nie', ''),
(NULL, 'KTM', '450 EXC', 2015, 'Austria', 'Motorcross', 'Nie', ''),
(NULL, 'KTM', '450 EXC Nighthawk Edition', 2015, 'Austria', 'Motorcross', 'Nie', ''),
(NULL, 'KTM', '450 EXC Redbull', 2015, 'Austria', 'Motorcross', 'Nie', ''),
(NULL, 'Suzuki', 'RM-Z 450', 2016, 'Japonia', 'Motorcross', 'Nie', ''),
(NULL, 'Yamaha', 'YZ450F', 2018, 'Japonia', 'Motorcross', 'Tak', 'Niebieski'),
(NULL, 'Creators', 'Concept Spruemeister SM71', 2023, 'USA', 'Alpha GP', 'Nie', ''),
(NULL, 'Creators', 'Yasiddesign X American Petrol', 2021, 'Wielka Brytania', 'Alpha GP', 'Nie', ''),
(NULL, 'IVORY-TOWER', 'Alpha IVT-R07', 2023, 'Francja', 'Alpha GP', 'Tak', 'Błękitny'),
(NULL, 'KTM', 'X-Bow R (Edition Two)', 2016, 'Austria', 'Alpha GP', 'Nie', ''),
(NULL, 'KTM', 'X-Bow R Spear Racing Ed.', 2016, 'Austria', 'Alpha GP', 'Nie', ''),
(NULL, 'PROTO', 'Alpha Mark X', 2020, 'Francja', 'Alpha GP', 'Nie', ''),
(NULL, 'PROTO', 'Concept Glow Motorsport', 2023, 'Francja', 'Alpha GP', 'Tak', 'Biały'),
(NULL, 'PROTO', 'Concept Pulse Performance', 2023, 'Francja', 'Alpha GP', 'Nie', ''),
(NULL, 'PROTO', 'Concept Sparrow Competition', 2023, 'Francja', 'Alpha GP', 'Nie', ''),
(NULL, 'PROTO', 'Concept Spear Racing', 2023, 'Francja', 'Alpha GP', 'Nie', ''),
(NULL, 'PROTO', 'Mark II', 2018, 'USA', 'Alpha GP', 'Tak', 'Żółty'),
(NULL, 'Red Bull', 'RB13', 2017, 'Wielka Brytania', 'Alpha GP', 'Nie', ''),
(NULL, 'Red Bull', 'RB14', 2018, 'Wielka Brytania', 'Alpha GP', 'Nie', ''),
(NULL, 'Red Bull', 'RB14 Disruption Edition', 2018, 'Wielka Brytania', 'Alpha GP', 'Nie', ''),
(NULL, 'Red Bull', 'RB18', 2022, 'Wielka Brytania', 'Alpha GP', 'Tak', 'Granatowy'),
(NULL, 'Chevrolet', 'Camaro SS', 2010, 'USA', 'Monster', 'Tak', 'Żółty'),
(NULL, 'Chevrolet', 'Silverado 1500', 2010, 'USA', 'Monster', 'Nie', ''),
(NULL, 'DeLorean', 'DMC-12 Monster truck Edition', 1981, 'USA', 'Monster', 'Nie', ''),
(NULL, 'Dodge', 'Challenger SRT-8 392', 2012, 'USA', 'Monster', 'Nie', ''),
(NULL, 'Ford', 'F-150 SVT Raptor', 2010, 'USA', 'Monster', 'Nie', ''),
(NULL, 'Ford', 'Mustang GT', 2011, 'USA', 'Monster', 'Tak', 'Błękitny'),
(NULL, 'Hummer', 'H1 Alpha', 2006, 'USA', 'Monster', 'Nie', ''),
(NULL, 'Jeep®', 'Grand Cherokee SRT8® 2012', 2012, 'USA', 'Monster', 'Nie', ''),
(NULL, 'Nissan', '370Z (Z34)', 2013, 'Japonia', 'Monster', 'Nie', ''),
(NULL, 'Nissan', 'Skyline GT-R (R34)', 2002, 'Japonia', 'Monster', 'Nie', ''),
(NULL, 'PROTO', 'Hotrod A1', 1930, 'USA', 'Monster', 'Nie', ''),
(NULL, 'PROTO', 'Hotrod A1 Royale Edition', 1930, 'USA', 'Monster', 'Nie', ''),
(NULL, 'Volkswagen', 'Kombi High School Edition', 1966, 'Niemcy', 'Monster', 'Nie', ''),
(NULL, 'Dodge', 'Charger R/T Hemi', 1969, 'USA', 'Demolition', 'Nie', ''),
(NULL, 'FENDER', 'Demolition Derby 1 Firenze', 1978, 'USA', 'Demolition', 'Nie', ''),
(NULL, 'FENDER', 'Demolition Derby 2 Rattlesnake', 1971, 'USA', 'Demolition', 'Nie', ''),
(NULL, 'FENDER', 'Demolition Derby 3 Frontiera', 1956, 'USA', 'Demolition', 'Nie', ''),
(NULL, 'FENDER', 'Demolition Derby 4 Vero', 1984, 'USA', 'Demolition', 'Nie', ''),
(NULL, 'FENDER', 'Demolition Derby 5 Bulk', 1975, 'USA', 'Demolition', 'Nie', ''),
(NULL, 'FENDER', 'Edition One Demolition Derby', 2022, 'USA', 'Demolition', 'Nie', ''),
(NULL, 'DCB', 'M31', 2018, 'USA', 'Powerboat', 'Nie', ''),
(NULL, 'Frauscher', '1414 Demon', 2016, 'Austria', 'Powerboat', 'Tak', 'Biały'),
(NULL, 'Ice Marine', 'Bladerunner 35', 2017, 'Wielka Brytania', 'Powerboat', 'Nie', ''),
(NULL, 'Lamborghini', 'Tecnomar for Lamborghini 63', 2021, 'Włochy', 'Powerboat', 'Nie', ''),
(NULL, 'PROTO', 'Offshore MK1', 2017, 'USA', 'Powerboat', 'Nie', ''),
(NULL, 'PROTO', 'Offshore MK2', 2018, 'USA', 'Powerboat', 'Tak', 'Srebrny'),
(NULL, 'PROTO', 'Water Rocket (ex-F1 Boat)', 2017, 'USA', 'Powerboat', 'Tak', 'Różowy'),
(NULL, 'Vector Powerboats', 'V40R', 2018, 'Wielka Brytania', 'Powerboat', 'Nie', ''),
(NULL, 'Beechcraft', 'Model 17 Staggerwing', 1945, 'USA', 'Plane', 'Nie', ''),
(NULL, 'Extra Aerobatic Planes', 'Extra 330 SC', 2009, 'Niemcy', 'Plane', 'Nie', ''),
(NULL, 'Granville Brothers Aircraft', 'Gee Bee R-1', 1934, 'USA', 'Plane', 'Nie', ''),
(NULL, 'Grumman', 'F8F Bearcat', 1945, 'USA', 'Plane', 'Tak', 'Zielony'),
(NULL, 'Harmon Rocket', 'Harmon Rocket III', 2018, 'USA', 'Plane', 'Tak', 'Biały'),
(NULL, 'North American', 'P-51 Mustang', 1945, 'USA', 'Plane', 'Tak', 'Czerwony'),
(NULL, 'Northrop Grumman', 'F4U Corsair', 1942, 'USA', 'Plane', 'Tak', 'Niebieski'),
(NULL, 'Pilatus', 'PC21', 2002, 'Szwajcaria', 'Plane', 'Nie', ''),
(NULL, 'Slick Aircraft', 'Slick 360 HP', 2017, 'RPA', 'Plane', 'Nie', ''),
(NULL, 'Supermarine', 'Spitfire Mk IX', 1942, 'Wielka Brytania', 'Plane', 'Nie', ''),
(NULL, 'WACO Aircraft', 'YMF-5D Super', 2018, 'USA', 'Plane', 'Nie', ''),
(NULL, 'Zivko', 'Edge 540 V3', 2016, 'USA', 'Plane', 'Nie', '');

-- Sezon 2, 6.12.2023
INSERT INTO pojazdy VALUES
(NULL, 'Audi', 'RS2 Avant', 1993, 'Niemcy', 'Street Tier 1', 'Tak', 'Żółty'),
(NULL, 'Audi', 'RS3 Sportback', 2022, 'Niemcy', 'Street Tier 2', 'Nie', ''),
(NULL, 'Audi', 'RS7 Sportback', 2022, 'Niemcy', 'Street Tier 2', 'Nie', ''),
(NULL, 'BMW', 'M2 Beehive Edition', 2017, 'Niemcy', 'Street Tier 1', 'Nie', ''),
(NULL, 'Chevrolet', '3100 Big-Block Edition', 1951, 'USA', 'Street Tier 1', 'Nie', ''),
(NULL, 'Chevrolet', 'Camaro RS Ghost Edition', 1969, 'USA', 'Street Tier 1', 'Nie', ''),
(NULL, 'Ford', 'GT Ruby Edition', 2005, 'USA', 'Street Tier 2', 'Nie', ''),
(NULL, 'Ford', 'Mustang Boss 429 Lime Edition', 1969, 'USA', 'Street Tier 1', 'Nie', ''),
(NULL, 'Hoonigan', 'Audi Scotto_s Coupe quattro', 1990, 'Niemcy', 'Street Tier 2', 'Nie', ''),
(NULL, 'Hoonigan', 'Chevrolet Big Block 632 Camaro', 1988, 'USA', 'Street Tier 2', 'Nie', ''),
(NULL, 'Hoonigan', 'Porsche Scotto_s 911 Turbo RWB', 1993, 'Niemcy', 'Street Tier 2', 'Nie', ''),
(NULL, 'Mazda', 'Cosmo Sport', 1967, 'Japonia', 'Street Tier 1', 'Tak', 'Czerwony'),
(NULL, 'Mazda', 'RX-3 Raigyo Edition', 1972, 'Japonia', 'Street Tier 1', 'Nie', ''),
(NULL, 'Mazda', 'RX-7 Turbo Outline Edition', 1988, 'Japonia', 'Street Tier 1', 'Nie', ''),
(NULL, 'Mitsubishi', 'Lancer Evolution IX', 2006, 'Japonia', 'Street Tier 2', 'Nie', ''),
(NULL, 'Nissan', 'GT-R Haru Edition', 2015, 'Japonia', 'Street Tier 2', 'Nie', ''),
(NULL, 'Volkswagen', 'Golf GTI Dash Edition', 2014, 'Niemcy', 'Street Tier 1', 'Nie', ''),
(NULL, 'Hoonigan', 'Audi S1 e-tron quattro Hoonitron', 2021, 'Niemcy', 'Drift', 'Tak', 'Srebrny'),
(NULL, 'Hoonigan', 'Ford Hoonicorn Mustang', 1965, 'USA', 'Drift', 'Tak', 'Czarny'),
(NULL, 'Hoonigan', 'Mitsubishi Lancer Evolution IX', 2006, 'Japonia', 'Drift', 'Tak', 'Czarny'),
(NULL, 'Mitsubishi', 'Lancer Evolution VI GSR', 1999, 'Japonia', 'Drift', 'Nie', ''),
(NULL, 'Mitsubishi', 'Lancer Evolution VI GSR Flow Edition', 1999, 'Japonia', 'Drift', 'Nie', ''),
(NULL, 'Hoonigan', 'Audi S1 e-tron quattro Hoonitron', 2021, 'Niemcy', 'Racing', 'Nie', ''),
(NULL, 'Bugatti', 'Chiron Super Sport 300+ Divine Edition', 2019, 'Francja', 'Hypercar', 'Nie', ''),
(NULL, 'Jaguar', 'C-X75 Concept Exo Edition', 2013, 'Wielka Brytania', 'Hypercar', 'Nie', ''),
(NULL, 'Noble', 'M500', 2022, 'Wielka Brytania', 'Hypercar', 'Nie', ''),
(NULL, 'Noble', 'M600', 2010, 'Wielka Brytania', 'Hypercar', 'Nie', ''),
(NULL, 'PROTO', 'Flashback', 1986, 'Francja', 'Hypercar', 'Nie', ''),
(NULL, 'PROTO', 'Lucky-One Marble Edition', 2022, 'Francja', 'Hypercar', 'Nie', '');

-- Sezon 5, 6.11.2024
INSERT INTO pojazdy VALUES
(NULL, 'Alfa Romeo', 'Giulia GTAm - Rival Edition', 2021, 'Włochy', 'Street Tier 2', 'Nie', 'Nie', ''),
(NULL, 'Audi', 'RS6 Avant Chase Squad Edition', 2021, 'Niemcy', 'Street Tier 2', 'Tak', 'Nie', 'Srebrny'),
(NULL, 'BMW', 'M5 CS', 2022, 'Niemcy', 'Street Tier 2', 'Tak', 'Nie', 'Srebrny'),
(NULL, 'BMW', 'M5 CS Rival Edition', 2022, 'Niemcy', 'Street Tier 2', 'Nie', 'Nie', ''),
(NULL, 'DeLorean', 'DMC-12 Rival Edition', 1981, 'USA', 'Street Tier 2', 'Nie', 'Nie', ''),
(NULL, 'Ferrari', 'Roma', 2020, 'Włochy', 'Street Tier 2', 'Nie', 'Nie', ''),
(NULL, 'Ford', 'Mustang Dark Horse Chase Squad Edition', 2024, 'USA', 'Street Tier 2', 'Nie', 'Nie', ''),
(NULL, 'Ford', 'Mustang Mach-E GT', 2021, 'USA', 'Street Tier 1', 'Nie', 'Nie', ''),
(NULL, 'IVORY-TOWER', 'Ogmios', 2024, 'Francja', 'Street Tier 2', 'Nie', 'Nie', ''),
(NULL, 'IVORY-TOWER', 'Ogmios Chase Squad Edition', 2024, 'Francja', 'Street Tier 2', 'Nie', 'Nie', ''),
(NULL, 'Liberty Walk', 'Honda NSX', 1992, 'Japonia', 'Street Tier 2', 'Nie', 'Nie', ''),
(NULL, 'Nissan', 'Skyline GT-R (R32)', 1989, 'Japonia', 'Street Tier 2', 'Tak', 'Nie', 'Pomarańczowy'),
(NULL, 'Pontiac', 'GTO Rival Edition', 1966, 'USA', 'Street Tier 2', 'Nie', 'Nie', ''),
(NULL, 'Porsche', '911 GT3 RS', 2023, 'Niemcy', 'Street Tier 2', 'Tak', 'Nie', 'Biały'),
(NULL, 'Bugatti', 'Veyron Barchetta Velvet Edition', 2015, 'Francja', 'Hypercar', 'Nie', 'Nie', ''),
(NULL, 'Creators', 'Tempesta Rival Edition', 2022, 'Włochy', 'Hypercar', 'Nie', 'Nie', ''),
(NULL, 'Creators', 'K.S. Death Racer Edition', 2020, 'Wielka Brytania', 'Hypercar', 'Nie', 'Nie', ''),
(NULL, 'IVORY-TOWER', 'Aezus Chase Squad Edition', 2024, 'Francja', 'Hypercar', 'Nie', 'Nie', ''),
(NULL, 'Maserati', 'MC20 Cielo', 2023, 'Włochy', 'Hypercar', 'Nie', 'Nie', ''),
(NULL, 'Mercedes-AMG', 'One', 2022, 'Niemcy', 'Hypercar', 'Nie', 'Nie', ''),
(NULL, 'Noble', 'M600 Lunar Year Edition', 2010, 'Wielka Brytania', 'Hypercar', 'Nie', 'Nie', ''),
(NULL, 'Porsche', '911 GT3 RS Chase Squad Edition', 2023, 'Niemcy', 'Hypercar', 'Nie', 'Nie', ''),
(NULL, 'Rimac', 'Nevera', 2022, 'Chorwacja', 'Hypercar', 'Tak', 'Nie', 'Niebieski'),
(NULL, 'Rimac', 'Nevera Time Attack Edition', 2023, 'Chorwacja', 'Hypercar', 'Nie', 'Nie', ''),
(NULL, 'W Motors', 'Lykan Hypersport Chase Squad Edition', 2017, 'ZEA', 'Hypercar', 'Nie', 'Nie', ''),
(NULL, 'PROTO', 'A500', 2016, 'Francja', 'Helikopter', 'Tak', 'Nie', 'Żółty'),
(NULL, 'PROTO', 'A500 Chase Squad Edition', 2016, 'Francja', 'Helikopter', 'Nie', 'Nie', '')
-- Sezon 6, 6.03.2025
INSERT INTO pojazdy VALUES
(NULL, 'Mini', 'John Cooper Works GP', 2020, 'Wielka Brytania', 'Street Tier 1', 'Nie', 'Nie', ''),
(NULL, 'BMW', 'M4 Red Bull Driftbrothers Ed.', 2024, 'Niemcy', 'Drift', 'Nie', 'Nie', ''),
(NULL, 'Ferrari', '488 GT3 AF Corse', 2016, 'Włochy', 'Racing', 'Tak', 'Nie', 'Granatowy'),
(NULL, 'IVORY-TOWER', 'Aezus GT', 2024, 'Francja', 'Racing', 'Nie', 'Nie', ''),
(NULL, 'KTM', 'X-Bow R Experience Red Bull Ring', 2016, 'Austria', 'Racing', 'Tak', 'Nie', 'Granatowy'),
(NULL, 'Red Bull', 'RB20', 2024, 'Wielka Brytania', 'Alpha GP', 'Tak', 'Nie', 'Granatowy'),
(NULL, 'Audi', 'RS Q e-tron', 2024, 'Niemcy', 'Rally Raid', 'Nie', 'Nie', ''),
(NULL, 'Ford', 'Fiesta Red Bull Ed.', 2017, 'USA', 'Rally', 'Nie', 'Nie', ''),
(NULL, 'Ford', 'Puma Hybrid Rally 1', 2022, 'USA', 'Rally', 'Tak', 'Nie', 'Niebieski'),
(NULL, 'Dassault Aviation', 'Alpha Jet', 1977, 'USA', 'Jet', 'Nie', 'Nie', ''),
(NULL, 'Extra Aerobatic Planes', 'Extra 330 SC Red Bull Ed.', 2009, 'USA', 'Plane', 'Nie', 'Nie', ''),
(NULL, 'Ford', 'F-150 Raptor Race Truck Red Bull Ed.', 2017, 'USA', 'Monster', 'Nie', 'Nie', ''),
(NULL, 'KTM', '450 EXC Robbie Maddison Ed.', 2015, 'Austria', 'Motorcross', 'Nie', 'Tak', ''),
(NULL, 'Mazda', 'RX7 Red Fury Edition', 2002, 'Japonia', 'Street Tier 2', 'Nie', 'Nie', ''),
(NULL, 'Radical', 'RXC 600R', 2024, 'Wielka Brytania', 'Racing', 'Nie', 'Nie', ''),
(NULL, 'Radical', 'SR10 XXR', 2024, 'Wielka Brytania', 'Racing', 'Nie', 'Nie', '')

-- Sezon 7, 2.07.2025
INSERT INTO pojazdy VALUES
(NULL, 'Ferrari', 'F50', 1995, 'Włochy', 'Street Tier 2', 'Tak', 'Nie', 'Biały', 'Dobra'),
(NULL, 'Ferrari', 'GTO', 1984, 'Włochy', 'Street Tier 2', 'Tak', 'Nie',  'Czerwony', 'Dobra'),
(NULL, 'MV Agusta', 'Brutale Dragster 800 RR', 2016, 'Włochy', 'Street Tier 2', 'Tak', 'Tak', 'Czerwony', 'Dobra'),
(NULL, 'MV Agusta', 'F4 RR', 2017, 'Włochy', 'Street Tier 2', 'Nie', 'Tak',  '', 'Dobra'),
(NULL, 'Triumph', 'Rocket 3R', 2021, 'Wielka Brytania', 'Street Tier 2', 'Nie', 'Tak',  '', 'Dobra'),
(NULL, 'Ferrari', 'F80', 2025, 'Włochy', 'Hypercar', 'Tak', 'Nie',  'Czerwony', 'Dobra'),
(NULL, 'Ferrari', 'SF90 Stradale Assetto Fiorano', 2020, 'Włochy', 'Hypercar', 'Tak', 'Nie',  'Czerwony', 'Dobra'),
(NULL, 'Genty', 'Akylone', 2024, 'Francja', 'Hypercar', 'Tak', 'Nie',  '', 'Dobra'),
(NULL, 'Audi', 'R8 LMS GT2', 2020, 'Niemcy', 'Racing', 'Nie', 'Nie',  '', 'Dobra'),
(NULL, 'Bugatti', 'Vision GT', 2015, 'Francja', 'Racing', 'Nie', 'Nie',  '', 'Dobra'),
(NULL, 'Porsche', '919 Clubsport', 2022, 'Niemcy', 'Racing', 'Nie', 'Nie',  '', 'Dobra'),
(NULL, 'Apollo', 'Project EVO', 2021, 'Niemcy', 'Hypercar', 'Nie', 'Nie',  '', 'Dobra'),
(NULL, 'Aston Martin', 'Vantage', 2024, 'Wielka Brytania', 'Street Tier 2', 'Nie', 'Nie',  '', 'Dobra'),
(NULL, 'IVORY-TOWER', 'Ogmios Rally Spec', 2024, 'Francja', 'Rally', 'Nie', 'Nie',  '', 'Dobra')

-- Sezon 8, 5.11.2025
INSERT INTO pojazdy VALUES
(NULL, 'BMW', 'M3', 2000, 'Niemcy', 'Street Tier 1', 'Nie', 'Nie', '', 'Dobra'),
(NULL, 'Volkswagen', 'Golf GTI 1800', 1982, 'Niemcy', 'Street Tier 1', 'Nie', 'Nie', '', 'Dobra'),
(NULL, 'BMW', 'M2 G87', 2023, 'Niemcy', 'Street Tier 2', 'Nie', 'Nie', '', 'Dobra'),
(NULL, 'BMW', 'M2 CS', 2025, 'Niemcy', 'Street Tier 2', 'Nie', 'Nie', '', 'Dobra'),
(NULL, 'BMW', 'M3 CS', 2023, 'Niemcy', 'Street Tier 2', 'Nie', 'Nie', '', 'Dobra'),
(NULL, 'BMW', 'M4 CSL', 2023, 'Niemcy', 'Street Tier 2', 'Nie', 'Nie', '', 'Dobra'),
(NULL, 'Ford', 'Shelby GR-1 Concept', 2004, 'USA', 'Street Tier 2', 'Nie', 'Nie', '', 'Dobra'),
(NULL, 'Mercedes-AMG', 'GT 63 4MATIC+ Coupe', 2023, 'Niemcy', 'Street Tier 2', 'Nie', 'Nie', '', 'Dobra'),
(NULL, 'Cadillac', 'Ciel Concept', 2011, 'USA', 'Hypercar', 'Nie', 'Nie', '', 'Dobra'),
(NULL, 'Ferrari', '12Cilindri', 2025, 'Włochy', 'Hypercar', 'Nie', 'Nie', '', 'Dobra'),
(NULL, 'Pagani', 'Imola', 2021, 'Włochy', 'Hypercar', 'Nie', 'Nie', '', 'Dobra'),
(NULL, 'Zenvo', 'Aurora Agil', 2026, 'Dania', 'Hypercar', 'Nie', 'Nie', '', 'Dobra'),
(NULL, 'BMW', '3.0 CSL', 1975, 'Niemcy', 'Racing', 'Nie', 'Nie', '', 'Dobra'),
(NULL, 'BMW', 'M Hybrid V8 nr 15', 2025, 'Niemcy', 'Racing', 'Nie', 'Nie', '', 'Dobra')

-- Sezon 9, 4.03.2026
INSERT INTO pojazdy VALUES
(NULL, 'PHAZR RC', 'Trickshot', 2026, 'Francja', 'Street Tier 1', 'Nie', 'Nie', '', 'Dobra'),
(NULL, 'PHAZR RC', 'Rust Bucket', 2026, 'Francja', 'Street Tier 1', 'Nie', 'Nie', '', 'Dobra'),
(NULL, 'PHAZR RC', 'General', 2026, 'Francja', 'Racing', 'Nie', 'Nie', '', 'Dobra'),
(NULL, 'PHAZR RC', 'General 2', 2026, 'Francja', 'Racing', 'Nie', 'Nie', '', 'Dobra'),
(NULL, 'Audi', 'Sport quattro S1 Pikes Peak', 1987, 'Niemcy', 'Rally', 'Nie', 'Nie', '', 'Dobra'),
(NULL, 'NASCAR', 'Next Gen Chevrolet Camaro ZL1', 2025, 'USA', 'Cup Car', 'Tak', 'Nie', 'Biały', 'Dobra'),
(NULL, 'NASCAR', 'Next Gen Chevrolet Camaro ZL1 - Hendrick #5', 2025, 'USA', 'Cup Car', 'Tak', 'Nie', 'Niebieski', 'Dobra'),
(NULL, 'NASCAR', 'Next Gen Chevrolet Camaro ZL1 - Hendrick #9', 2025, 'USA', 'Cup Car', 'Nie', 'Nie', '', 'Dobra'),
(NULL, 'NASCAR', 'Next Gen Chevrolet Camaro ZL1 - Hendrick #24', 2025, 'USA', 'Cup Car', 'Nie', 'Nie', '', 'Dobra'),
(NULL, 'NASCAR', 'Next Gen Chevrolet Camaro ZL1 - RCR #8', 2025, 'USA', 'Cup Car', 'Nie', 'Nie', '', 'Dobra'),
(NULL, 'NASCAR', 'Next Gen Chevrolet Camaro ZL1 - Trackhouse #1', 2025, 'USA', 'Cup Car', 'Nie', 'Nie', '', 'Dobra'),
(NULL, 'NASCAR', 'Next Gen Chevrolet Camaro ZL1 - Trackhouse #88', 2025, 'USA', 'Cup Car', 'Nie', 'Nie', '', 'Dobra'),
(NULL, 'Chevrolet', 'Impala Sport Sedan', 1967, 'USA', 'Cup Car', 'Tak', 'Nie', 'Biały', 'Dobra'),
(NULL, 'NASCAR', 'Next Gen Ford Mustang Dark Horse', 2025, 'USA', 'Cup Car', 'Tak', 'Nie', 'Niebieski', 'Dobra'),
(NULL, 'NASCAR', 'Next Gen Ford Mustang Dark Horse - Penske #12', 2025, 'USA', 'Cup Car', 'Nie', 'Nie', '', 'Dobra'),
(NULL, 'NASCAR', 'Next Gen Ford Mustang Dark Horse - Penske #22', 2025, 'USA', 'Cup Car', 'Nie', 'Nie', '', 'Dobra'),
(NULL, 'NASCAR', 'Next Gen Ford Mustang Dark Horse - RFK #6', 2025, 'USA', 'Cup Car', 'Nie', 'Nie', '', 'Dobra'),
(NULL, 'NASCAR', 'Next Gen Toyota Camry', 2025, 'USA', 'Cup Car', 'Tak', 'Nie', 'Biały', 'Dobra'),
(NULL, 'NASCAR', 'Next Gen Toyota Camry - 23XI #23', 2025, 'USA', 'Cup Car', 'Nie', 'Nie', '', 'Dobra'),
(NULL, 'NASCAR', 'Next Gen Toyota Camry - 23XI #45', 2025, 'USA', 'Cup Car', 'Nie', 'Nie', '', 'Dobra'),
(NULL, 'NASCAR', 'Next Gen Toyota Camry - JGR #19', 2025, 'USA', 'Cup Car', 'Nie', 'Nie', '', 'Dobra'),
(NULL, 'NASCAR', 'Next Gen Toyota Camry - JGR #20', 2025, 'USA', 'Cup Car', 'Nie', 'Nie', '', 'Dobra'),
(NULL, 'Proto', 'Henson Custom', 2025, 'Francja', 'Cup Car', 'Tak', 'Nie', 'Niebieski', 'Dobra'),
(NULL, 'Porsche', '935', 2019, 'Niemcy', 'Racing', 'Tak', 'Nie', 'Niebieski', 'Dobra'),
(NULL, 'Hennessey', 'Venom F5', 2020, 'USA', 'Hypercar', 'Tak', 'Nie', 'Biały', 'Dobra'),
(NULL, 'Apollo', 'Sport', 2008, 'Niemcy', 'Hypercar', 'Nie', 'Nie', '', 'Dobra'),
(NULL, 'Porsche', '911 GT3 RS Tribute to Carrera RS Package', 2023, 'Niemcy', 'Street Tier 2', 'Nie', 'Nie', '', 'Dobra'),
(NULL, 'Traxxas', 'X-Maxx Ultimate', 2025, 'Francja', 'Rally Raid', 'Nie', 'Nie', '', 'Dobra'),
(NULL, 'PHAZR RC', 'Comet', 2025, 'Francja', 'Street Tier 1', 'Nie', 'Nie', '', 'Dobra'),
(NULL, 'PHAZR RC', 'Coyote', 2025, 'Francja', 'Rally Raid', 'Nie', 'Nie', '', 'Dobra'),
(NULL, 'Honda', 'Civic Type R Red Panther Ed.', 2016, 'Japonia', 'Street Tier 1', 'Nie', 'Nie', '', 'Dobra'),
(NULL, 'Touring Superleggera', 'Arese RH95', 2025, 'Włochy', 'Hypercar', 'Tak', 'Nie', 'Żółty', 'Dobra')